"""
Blender 5.1+ character and external Three.js animation exporter.

Final output:
    character.glb
    animationClipFactory.ts
    animations/
        ActionName.ts
        index.ts

Run this file from Blender's Text Editor. The final GLB never contains
animation clips. Animation values are extracted from a temporary sampled GLB
so they exactly match Blender's glTF coordinate/bone conversion.
"""

import bpy
import json
import math
import os
import re
import struct
import traceback


# ============================================================================
# Configuration
# ============================================================================

OUTPUT_DIRECTORY = "//threejs_character/"
GLB_FILENAME = "character.glb"
EXPORT_ALL_ACTIONS = True
ACTIONS_TO_EXCLUDE = {
    # "T-Pose",
}
DECIMAL_PRECISION = 5
SAMPLING_FPS = 30
SAMPLE_BAKED_ANIMATION = True
EXPORT_MATERIALS = True
EXPORT_TEXTURES = True
TEXTURE_IMAGE_FORMAT = "AUTO"  # AUTO, JPEG, WEBP, or NONE
TEXTURE_QUALITY = 85
EXPORT_MORPH_TARGETS = True
EXPORT_VERTEX_COLORS = True
EXPORT_TANGENTS = False
EXPORT_CUSTOM_PROPERTIES = False
MESH_COMPRESSION = "NONE"  # NONE or DRACO
DRACO_COMPRESSION_LEVEL = 6
DRACO_POSITION_QUANTIZATION = 14
DRACO_NORMAL_QUANTIZATION = 10
DRACO_TEXCOORD_QUANTIZATION = 12
DRACO_COLOR_QUANTIZATION = 10
DRACO_GENERIC_QUANTIZATION = 12


# ============================================================================
# Constants
# ============================================================================

_GENERATED_MARKER = "// Generated by Blender Three.js Character Exporter"
_STAGING_FILENAME = ".__threejs_animation_staging__.glb"
_TRANSFORM_WIDTHS = {
    "delta_location": 3,
    "delta_rotation_euler": 3,
    "delta_rotation_quaternion": 4,
    "delta_scale": 3,
    "location": 3,
    "rotation_axis_angle": 4,
    "rotation_euler": 3,
    "rotation_quaternion": 4,
    "scale": 3,
    "value": 1,
}
_COMPONENT_FORMATS = {
    5120: "b",
    5121: "B",
    5122: "h",
    5123: "H",
    5125: "I",
    5126: "f",
}
_ACCESSOR_WIDTHS = {
    "SCALAR": 1,
    "VEC2": 2,
    "VEC3": 3,
    "VEC4": 4,
    "MAT2": 4,
    "MAT3": 9,
    "MAT4": 16,
}
_TS_RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger",
    "default", "delete", "do", "else", "enum", "export", "extends",
    "false", "finally", "for", "function", "if", "implements", "import",
    "in", "instanceof", "interface", "let", "new", "null", "package",
    "private", "protected", "public", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "var", "void",
    "while", "with", "yield",
}
_WINDOWS_RESERVED = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}


# ============================================================================
# Scene and Action discovery
# ============================================================================

def _skinned_meshes_for_armature(armature):
    meshes = []
    for obj in bpy.context.scene.objects:
        if obj.type != "MESH":
            continue
        uses_armature = any(
            modifier.type == "ARMATURE" and modifier.object == armature
            for modifier in obj.modifiers
        )
        parented_to_armature = (
            obj.parent == armature and obj.parent_type in {"ARMATURE", "BONE"}
        )
        if uses_armature or parented_to_armature:
            meshes.append(obj)
    return sorted(meshes, key=lambda obj: obj.name)


def _find_primary_armature():
    candidates = []
    for armature in (obj for obj in bpy.context.scene.objects
                     if obj.type == "ARMATURE"):
        meshes = _skinned_meshes_for_armature(armature)
        vertex_count = sum(len(mesh.data.vertices) for mesh in meshes)
        candidates.append((len(meshes), vertex_count, armature.name,
                           armature, meshes))

    if not candidates:
        raise RuntimeError("No Armature exists in the current scene.")

    candidates.sort(key=lambda item: (item[0], item[1], item[2]), reverse=True)
    mesh_count, _vertices, _name, armature, meshes = candidates[0]
    if mesh_count == 0:
        raise RuntimeError(
            f"Found Armature '{armature.name}', but no meshes are skinned to it."
        )
    return armature, meshes


def _collect_character_objects(armature, meshes):
    result = {armature, *meshes}
    pending = list(result)
    while pending:
        obj = pending.pop()
        if obj.parent and obj.parent not in result:
            result.add(obj.parent)
            pending.append(obj.parent)
    return sorted(result, key=lambda obj: obj.name)


def _iter_action_fcurve_collections(action):
    found_slotted = False
    for layer in getattr(action, "layers", []):
        for strip in layer.strips:
            for channelbag in getattr(strip, "channelbags", []):
                found_slotted = True
                yield channelbag.fcurves
    if found_slotted:
        return
    try:
        yield action.fcurves
    except (AttributeError, RuntimeError):
        pass


def _iter_action_fcurves(action):
    for collection in _iter_action_fcurve_collections(action):
        yield from collection


def _action_has_keyframes(action):
    return any(
        len(fcurve.keyframe_points) > 0 or len(fcurve.sampled_points) > 0
        for fcurve in _iter_action_fcurves(action)
    )


def _actions_used_by_id(data_block):
    result = set()
    animation_data = getattr(data_block, "animation_data", None)
    if not animation_data:
        return result
    if animation_data.action:
        result.add(animation_data.action)
    for track in animation_data.nla_tracks:
        for strip in track.strips:
            if strip.action:
                result.add(strip.action)
    return result


def _find_character_actions(armature, meshes):
    used = _actions_used_by_id(armature)
    shape_key_names = set()
    for mesh in meshes:
        used.update(_actions_used_by_id(mesh))
        shape_keys = mesh.data.shape_keys
        if shape_keys and EXPORT_MORPH_TARGETS:
            used.update(_actions_used_by_id(shape_keys))
            shape_key_names.update(key.name for key in shape_keys.key_blocks)

    actions = set(used)
    if EXPORT_ALL_ACTIONS:
        bone_names = set(armature.data.bones.keys())
        bone_pattern = re.compile(r'pose\.bones\["((?:\\.|[^"])*)"\]')
        shape_pattern = re.compile(r'key_blocks\["((?:\\.|[^"])*)"\]\.value')
        for action in bpy.data.actions:
            for fcurve in _iter_action_fcurves(action):
                bone_match = bone_pattern.search(fcurve.data_path)
                if bone_match and bone_match.group(1) in bone_names:
                    actions.add(action)
                    break
                shape_match = shape_pattern.search(fcurve.data_path)
                if shape_match and shape_match.group(1) in shape_key_names:
                    actions.add(action)
                    break

    excluded = {name.casefold() for name in ACTIONS_TO_EXCLUDE}
    return sorted(
        (action for action in actions
         if action.name.casefold() not in excluded
         and _action_has_keyframes(action)),
        key=lambda action: action.name.casefold(),
    )


# ============================================================================
# Reversible workaround for malformed Blender/glTF F-curves
# ============================================================================

def _is_unsafe_fcurve(fcurve):
    target = fcurve.data_path.rsplit(".", 1)[-1]
    if target.startswith("["):
        target = ""
    target_width = _TRANSFORM_WIDTHS.get(target, 1)
    return fcurve.array_index < 0 or fcurve.array_index >= target_width


def _quarantine_unsafe_fcurves():
    quarantine = bpy.data.actions.new("__TJS_EXPORT_QUARANTINE__")
    slot = quarantine.slots.new("SCENE", "TJS Export Quarantine")
    layer = quarantine.layers.new("Quarantine")
    strip = layer.strips.new(type="KEYFRAME")
    destination = strip.channelbags.new(slot).fcurves
    records = []

    for action in list(bpy.data.actions):
        if action == quarantine:
            continue
        for collection in _iter_action_fcurve_collections(action):
            for fcurve in list(collection):
                if not _is_unsafe_fcurve(fcurve):
                    continue
                copy = destination.new_from_fcurve(fcurve)
                records.append((collection, copy, action.name,
                                fcurve.data_path, fcurve.array_index))
                collection.remove(fcurve)
    return quarantine, records


def _restore_quarantined_fcurves(quarantine, records):
    for collection, copy, _action_name, _path, _index in records:
        collection.new_from_fcurve(copy)
    if quarantine:
        bpy.data.actions.remove(quarantine)


# ============================================================================
# GLB export and parsing
# ============================================================================

def _export_glb(filepath, objects, *, animations, frame_step=1):
    bpy.ops.object.mode_set(mode="OBJECT") if bpy.context.object and \
        bpy.context.object.mode != "OBJECT" else None
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.hide_set(False)
        obj.hide_viewport = False
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]

    image_format = (
        TEXTURE_IMAGE_FORMAT
        if EXPORT_MATERIALS and EXPORT_TEXTURES
        else "NONE"
    )
    use_draco = MESH_COMPRESSION == "DRACO" and not animations
    options = dict(
        filepath=filepath,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=False,
        export_materials="EXPORT" if EXPORT_MATERIALS else "NONE",
        export_image_format=image_format,
        export_jpeg_quality=TEXTURE_QUALITY,
        export_image_quality=TEXTURE_QUALITY,
        export_vertex_color="MATERIAL" if EXPORT_VERTEX_COLORS else "NONE",
        export_all_vertex_colors=EXPORT_VERTEX_COLORS,
        export_tangents=EXPORT_TANGENTS,
        export_extras=EXPORT_CUSTOM_PROPERTIES,
        export_draco_mesh_compression_enable=use_draco,
        export_draco_mesh_compression_level=DRACO_COMPRESSION_LEVEL,
        export_draco_position_quantization=DRACO_POSITION_QUANTIZATION,
        export_draco_normal_quantization=DRACO_NORMAL_QUANTIZATION,
        export_draco_texcoord_quantization=DRACO_TEXCOORD_QUANTIZATION,
        export_draco_color_quantization=DRACO_COLOR_QUANTIZATION,
        export_draco_generic_quantization=DRACO_GENERIC_QUANTIZATION,
        export_skins=True,
        export_def_bones=False,
        export_rest_position_armature=True,
        export_leaf_bone=False,
        export_morph=EXPORT_MORPH_TARGETS,
        export_animations=animations,
    )
    if animations:
        options.update(
            export_animation_mode="ACTIONS",
            export_merge_animation="ACTION",
            export_force_sampling=SAMPLE_BAKED_ANIMATION,
            export_frame_step=frame_step,
            export_optimize_animation_size=True,
            export_optimize_animation_keep_anim_armature=True,
            export_anim_single_armature=True,
            export_anim_slide_to_zero=True,
            export_morph_animation=EXPORT_MORPH_TARGETS,
            export_extra_animations=False,
        )
    else:
        options.update(export_morph_animation=False)

    result = bpy.ops.export_scene.gltf(**options)
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender cancelled GLB export: {filepath}")


def _read_glb(filepath):
    with open(filepath, "rb") as handle:
        header = handle.read(12)
        if len(header) != 12:
            raise ValueError(f"Invalid GLB header: {filepath}")
        magic, version, total_length = struct.unpack("<4sII", header)
        if magic != b"glTF" or version != 2:
            raise ValueError(f"Not a glTF 2.0 GLB: {filepath}")

        document = None
        binary = b""
        while handle.tell() < total_length:
            chunk_header = handle.read(8)
            if len(chunk_header) != 8:
                raise ValueError("Truncated GLB chunk header.")
            chunk_length, chunk_type = struct.unpack("<II", chunk_header)
            chunk = handle.read(chunk_length)
            if len(chunk) != chunk_length:
                raise ValueError("Truncated GLB chunk.")
            if chunk_type == 0x4E4F534A:
                document = json.loads(
                    chunk.rstrip(b"\x00 \t\r\n").decode("utf-8")
                )
            elif chunk_type == 0x004E4942:
                binary = chunk

    if document is None:
        raise ValueError("GLB contains no JSON document.")
    return document, binary


def _normalize_component(value, component_type):
    if component_type == 5120:
        return max(value / 127.0, -1.0)
    if component_type == 5121:
        return value / 255.0
    if component_type == 5122:
        return max(value / 32767.0, -1.0)
    if component_type == 5123:
        return value / 65535.0
    return value


def _read_accessor(document, binary, accessor_index):
    accessor = document["accessors"][accessor_index]
    width = _ACCESSOR_WIDTHS[accessor["type"]]
    count = accessor["count"]
    component_type = accessor["componentType"]
    component_format = _COMPONENT_FORMATS[component_type]
    component_size = struct.calcsize("<" + component_format)
    element_size = component_size * width

    if "bufferView" not in accessor:
        return [[0.0] * width for _ in range(count)]

    view = document["bufferViews"][accessor["bufferView"]]
    offset = view.get("byteOffset", 0) + accessor.get("byteOffset", 0)
    stride = view.get("byteStride", element_size)
    unpack_format = "<" + component_format * width
    normalized = accessor.get("normalized", False)
    values = []

    for index in range(count):
        item = list(struct.unpack_from(
            unpack_format, binary, offset + index * stride
        ))
        if normalized:
            item = [
                _normalize_component(value, component_type)
                for value in item
            ]
        values.append(item)
    return values


# ============================================================================
# Track extraction and optimization
# ============================================================================

def _node_rest_value(document, node_index, path):
    node = document["nodes"][node_index]
    if path == "translation":
        return node.get("translation", [0.0, 0.0, 0.0])
    if path == "rotation":
        return node.get("rotation", [0.0, 0.0, 0.0, 1.0])
    if path == "scale":
        return node.get("scale", [1.0, 1.0, 1.0])
    return None


def _three_node_names(document):
    """Mirror GLTFLoader/PropertyBinding node-name sanitizing and uniqueness."""
    result = {}
    used = {}
    for index, node in enumerate(document.get("nodes", [])):
        original = node.get("name") or f"node_{index}"
        sanitized = re.sub(r"\s", "_", original)
        sanitized = re.sub(r"[\[\]\.:/]", "", sanitized) or f"node_{index}"
        duplicate_index = used.get(sanitized, 0)
        used[sanitized] = duplicate_index + 1
        result[index] = (
            sanitized if duplicate_index == 0
            else f"{sanitized}_{duplicate_index}"
        )
    return result


def _quat_normalize(quaternion):
    length = math.sqrt(sum(value * value for value in quaternion))
    if length <= 1e-12:
        return [0.0, 0.0, 0.0, 1.0]
    return [value / length for value in quaternion]


def _quat_slerp(first, second, factor):
    first = _quat_normalize(first)
    second = _quat_normalize(second)
    dot = sum(a * b for a, b in zip(first, second))
    if dot < 0.0:
        second = [-value for value in second]
        dot = -dot
    dot = min(1.0, max(-1.0, dot))
    if dot > 0.9995:
        return _quat_normalize([
            a + factor * (b - a) for a, b in zip(first, second)
        ])
    angle = math.acos(dot)
    sine = math.sin(angle)
    left = math.sin((1.0 - factor) * angle) / sine
    right = math.sin(factor * angle) / sine
    return [left * a + right * b for a, b in zip(first, second)]


def _close_values(first, second, epsilon):
    return len(first) == len(second) and all(
        abs(a - b) <= epsilon for a, b in zip(first, second)
    )


def _interpolated_value(first, second, factor, property_name):
    if property_name == "quaternion":
        return _quat_slerp(first, second, factor)
    return [a + factor * (b - a) for a, b in zip(first, second)]


def _optimize_track(times, values, property_name, rest_value):
    if not times or len(times) != len(values):
        return None
    epsilon = 10.0 ** (-DECIMAL_PRECISION)

    if property_name == "quaternion":
        normalized = []
        for value in values:
            value = _quat_normalize(value)
            if normalized and sum(
                a * b for a, b in zip(normalized[-1], value)
            ) < 0.0:
                value = [-component for component in value]
            normalized.append(value)
        values = normalized

    if rest_value is not None and all(
        _close_values(value, rest_value, epsilon) for value in values
    ):
        return None

    if len(times) > 2:
        kept_indices = [0]
        for index in range(1, len(times) - 1):
            previous = kept_indices[-1]
            following = index + 1
            span = times[following] - times[previous]
            if abs(span) <= 1e-12:
                kept_indices.append(index)
                continue
            factor = (times[index] - times[previous]) / span
            predicted = _interpolated_value(
                values[previous], values[following], factor, property_name
            )
            if not _close_values(values[index], predicted, epsilon):
                kept_indices.append(index)
        kept_indices.append(len(times) - 1)
        times = [times[index] for index in kept_indices]
        values = [values[index] for index in kept_indices]

    rounded_times = [_round_float(value) for value in times]
    rounded_values = [
        [_round_float(component) for component in value]
        for value in values
    ]
    return rounded_times, rounded_values


def _round_float(value):
    rounded = round(float(value), DECIMAL_PRECISION)
    return 0.0 if abs(rounded) < 10.0 ** (-DECIMAL_PRECISION) else rounded


def _take_cubic_spline_values(rows):
    return [rows[index] for index in range(1, len(rows), 3)]


def _extract_standard_track(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    path = channel["target"]["path"]
    target_name = node_names[node_index]
    times = [row[0] for row in _read_accessor(
        document, binary, sampler["input"]
    )]
    values = _read_accessor(document, binary, sampler["output"])
    interpolation = sampler.get("interpolation", "LINEAR")
    if interpolation == "CUBICSPLINE":
        values = _take_cubic_spline_values(values)

    property_map = {
        "translation": "position",
        "rotation": "quaternion",
        "scale": "scale",
    }
    property_name = property_map[path]
    optimized = _optimize_track(
        times, values, property_name,
        _node_rest_value(document, node_index, path),
    )
    if not optimized:
        return None
    times, values = optimized
    return {
        "target": target_name,
        "property": property_name,
        "times": times,
        "values": [component for value in values for component in value],
        **({"interpolation": "discrete"}
           if interpolation == "STEP" else {}),
    }


def _extract_weight_tracks(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    node = document["nodes"][node_index]
    target_name = node_names[node_index]
    mesh = document["meshes"][node["mesh"]]
    target_names = mesh.get("extras", {}).get("targetNames", [])
    times = [row[0] for row in _read_accessor(
        document, binary, sampler["input"]
    )]
    rows = _read_accessor(document, binary, sampler["output"])
    flat = [component for row in rows for component in row]
    interpolation = sampler.get("interpolation", "LINEAR")

    divisor = len(times) * (3 if interpolation == "CUBICSPLINE" else 1)
    target_count = len(flat) // divisor if divisor else 0
    if target_count == 0:
        return []

    if interpolation == "CUBICSPLINE":
        sampled = []
        block = target_count * 3
        for index in range(len(times)):
            start = index * block + target_count
            sampled.append(flat[start:start + target_count])
    else:
        sampled = [
            flat[index * target_count:(index + 1) * target_count]
            for index in range(len(times))
        ]

    rest_weights = node.get("weights", mesh.get(
        "weights", [0.0] * target_count
    ))
    tracks = []
    for target_index in range(target_count):
        values = [[sample[target_index]] for sample in sampled]
        rest = [rest_weights[target_index]
                if target_index < len(rest_weights) else 0.0]
        optimized = _optimize_track(
            times, values,
            f"morphTargetInfluences[{target_index}]",
            rest,
        )
        if not optimized:
            continue
        track_times, track_values = optimized
        track = {
            "target": target_name,
            "property": f"morphTargetInfluences[{target_index}]",
            "times": track_times,
            "values": [value[0] for value in track_values],
        }
        if target_index < len(target_names):
            track["morphTarget"] = target_names[target_index]
        if interpolation == "STEP":
            track["interpolation"] = "discrete"
        tracks.append(track)
    return tracks


def _extract_animation_data(document, binary, wanted_names, effective_fps):
    grouped = {}
    node_names = _three_node_names(document)
    for animation_index, animation in enumerate(
        document.get("animations", [])
    ):
        name = animation.get("name") or f"Animation_{animation_index + 1}"
        if name not in wanted_names:
            continue
        entry = grouped.setdefault(name, {"name": name, "tracks": []})
        for channel in animation.get("channels", []):
            sampler = animation["samplers"][channel["sampler"]]
            path = channel.get("target", {}).get("path")
            if path in {"translation", "rotation", "scale"}:
                track = _extract_standard_track(
                    document, binary, channel, sampler, node_names
                )
                if track:
                    entry["tracks"].append(track)
            elif path == "weights":
                entry["tracks"].extend(_extract_weight_tracks(
                    document, binary, channel, sampler, node_names
                ))

    result = []
    for name in sorted(grouped, key=str.casefold):
        entry = grouped[name]
        duration = max(
            (max(track["times"]) for track in entry["tracks"]
             if track["times"]),
            default=0.0,
        )
        entry["duration"] = _round_float(duration)
        entry["fps"] = _round_float(effective_fps)
        entry["tracks"].sort(
            key=lambda track: (track["target"], track["property"])
        )
        result.append(entry)
    return result


# ============================================================================
# TypeScript generation
# ============================================================================

def _safe_identifier(name):
    identifier = re.sub(r"\W+", "_", name, flags=re.UNICODE).strip("_")
    if not identifier:
        identifier = "Animation"
    if identifier[0].isdigit() or identifier in _TS_RESERVED:
        identifier = f"Animation_{identifier}"
    return identifier


def _safe_filename(name):
    filename = re.sub(r'[<>:"/\\|?*\x00-\x1F]+', "_", name).strip(" .")
    if not filename:
        filename = "Animation"
    if filename.upper() in _WINDOWS_RESERVED:
        filename = f"Animation_{filename}"
    return filename


def _unique_names(animations):
    used_identifiers = set()
    used_files = set()
    result = []
    for animation in animations:
        base_identifier = _safe_identifier(animation["name"])
        base_file = _safe_filename(animation["name"])
        identifier = base_identifier
        filename = base_file
        suffix = 2
        while (identifier.casefold() in used_identifiers or
               filename.casefold() in used_files):
            identifier = f"{base_identifier}_{suffix}"
            filename = f"{base_file}_{suffix}"
            suffix += 1
        used_identifiers.add(identifier.casefold())
        used_files.add(filename.casefold())
        result.append((animation, identifier, filename))
    return result


def _atomic_write(filepath, content):
    temporary = filepath + ".tmp"
    with open(temporary, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, filepath)


def _remove_old_generated_animation_files(animation_dir):
    if not os.path.isdir(animation_dir):
        return
    for filename in os.listdir(animation_dir):
        if not filename.endswith(".ts"):
            continue
        filepath = os.path.join(animation_dir, filename)
        try:
            with open(filepath, "r", encoding="utf-8") as handle:
                first_line = handle.readline().rstrip("\r\n")
            if first_line == _GENERATED_MARKER:
                os.remove(filepath)
        except OSError:
            continue


def _animation_module(animation, identifier):
    compact = json.dumps(
        animation, ensure_ascii=False, separators=(",", ":"), allow_nan=False
    )
    return (
        f"{_GENERATED_MARKER}\n"
        'import type { AnimationData } from "../animationClipFactory";\n\n'
        f"export const {identifier} = {compact} as const "
        "satisfies AnimationData;\n"
        f"export default {identifier};\n"
    )


def _index_module(named_animations):
    imports = "\n".join(
        f'import {{ {identifier} }} from "./{filename}";'
        for _animation, identifier, filename in named_animations
    )
    exports = ", ".join(
        identifier for _animation, identifier, _filename in named_animations
    )
    return (
        f"{_GENERATED_MARKER}\n"
        f"{imports}\n\n"
        f"export {{ {exports} }};\n"
        f"export const animations = [{exports}] as const;\n"
    )


def _factory_module():
    return f"""{_GENERATED_MARKER}
import * as THREE from "three";

export type AnimationProperty =
  | "position"
  | "quaternion"
  | "scale"
  | `morphTargetInfluences[${{number}}]`;

export interface AnimationTrackData {{
  readonly target: string;
  readonly property: AnimationProperty;
  readonly times: readonly number[];
  readonly values: readonly number[];
  readonly interpolation?: "linear" | "discrete";
  readonly morphTarget?: string;
}}

export interface AnimationData {{
  readonly name: string;
  readonly duration: number;
  readonly fps: number;
  readonly tracks: readonly AnimationTrackData[];
}}

function createTrack(track: AnimationTrackData): THREE.KeyframeTrack {{
  const binding = `${{track.target}}.${{track.property}}`;
  const times = Array.from(track.times);
  const values = Array.from(track.values);
  let result: THREE.KeyframeTrack;

  if (track.property === "quaternion") {{
    result = new THREE.QuaternionKeyframeTrack(binding, times, values);
  }} else if (
    track.property === "position" ||
    track.property === "scale"
  ) {{
    result = new THREE.VectorKeyframeTrack(binding, times, values);
  }} else {{
    result = new THREE.NumberKeyframeTrack(binding, times, values);
  }}

  if (track.interpolation === "discrete") {{
    result.setInterpolation(THREE.InterpolateDiscrete);
  }}
  return result;
}}

export function createAnimationClip(
  animation: AnimationData,
): THREE.AnimationClip {{
  const tracks = animation.tracks.map(createTrack);
  return new THREE.AnimationClip(animation.name, animation.duration, tracks);
}}

export function createAnimationClips(
  animations: readonly AnimationData[],
): THREE.AnimationClip[] {{
  return animations.map(createAnimationClip);
}}
"""


# ============================================================================
# Export orchestration and reporting
# ============================================================================

def _human_size(byte_count):
    size = float(byte_count)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024.0 or unit == "GB":
            return f"{size:.1f} {unit}"
        size /= 1024.0


def _snapshot_scene_state(objects):
    return {
        "active": (bpy.context.view_layer.objects.active.name
                   if bpy.context.view_layer.objects.active else None),
        "selected": [obj.name for obj in bpy.context.selected_objects],
        "hidden": {
            obj.name: (obj.hide_get(), obj.hide_viewport)
            for obj in objects
        },
        "frame": bpy.context.scene.frame_current,
    }


def _restore_scene_state(state):
    for name, (hidden, hide_viewport) in state["hidden"].items():
        obj = bpy.data.objects.get(name)
        if obj:
            obj.hide_set(hidden)
            obj.hide_viewport = hide_viewport
    try:
        bpy.ops.object.select_all(action="DESELECT")
    except Exception:
        pass
    for name in state["selected"]:
        obj = bpy.data.objects.get(name)
        if obj and not obj.hide_get() and not obj.hide_viewport:
            obj.select_set(True)
    active = bpy.data.objects.get(state["active"]) if state["active"] else None
    if active:
        bpy.context.view_layer.objects.active = active
    bpy.context.scene.frame_set(state["frame"])


def export_character_and_animations():
    if not GLB_FILENAME.lower().endswith(".glb"):
        raise ValueError("GLB_FILENAME must end with '.glb'.")
    if os.path.basename(GLB_FILENAME) != GLB_FILENAME:
        raise ValueError("GLB_FILENAME must be a filename, not a path.")
    if OUTPUT_DIRECTORY.startswith("//") and not bpy.data.filepath:
        raise RuntimeError(
            "Save the .blend file first or configure an absolute "
            "OUTPUT_DIRECTORY."
        )
    if DECIMAL_PRECISION < 3 or DECIMAL_PRECISION > 9:
        raise ValueError("DECIMAL_PRECISION must be between 3 and 9.")
    if SAMPLING_FPS <= 0:
        raise ValueError("SAMPLING_FPS must be greater than zero.")

    output_dir = bpy.path.abspath(OUTPUT_DIRECTORY)
    animation_dir = os.path.join(output_dir, "animations")
    glb_path = os.path.join(output_dir, GLB_FILENAME)
    staging_path = os.path.join(output_dir, _STAGING_FILENAME)
    factory_path = os.path.join(output_dir, "animationClipFactory.ts")
    index_path = os.path.join(animation_dir, "index.ts")

    armature, meshes = _find_primary_armature()
    character_objects = _collect_character_objects(armature, meshes)
    actions = _find_character_actions(armature, meshes)
    wanted_names = {action.name for action in actions}

    scene_fps = (
        bpy.context.scene.render.fps /
        bpy.context.scene.render.fps_base
    )
    frame_step = max(1, int(round(scene_fps / SAMPLING_FPS)))
    effective_fps = scene_fps / frame_step

    os.makedirs(animation_dir, exist_ok=True)
    state = _snapshot_scene_state(character_objects)
    quarantine = None
    quarantine_records = []
    generated_files = []

    try:
        print(f"[Three.js Export] Primary Armature: {armature.name}")
        print(
            f"[Three.js Export] Skinned meshes: "
            f"{', '.join(mesh.name for mesh in meshes)}"
        )

        _export_glb(glb_path, character_objects, animations=False)
        character_document, _character_binary = _read_glb(glb_path)
        if character_document.get("animations"):
            raise RuntimeError("character.glb unexpectedly contains animations.")
        if not character_document.get("skins"):
            raise RuntimeError(
                "character.glb contains no skin. Check the Armature modifiers "
                "and vertex groups on the detected meshes."
            )
        generated_files.append(glb_path)

        animation_data = []
        if actions:
            quarantine, quarantine_records = _quarantine_unsafe_fcurves()
            if quarantine_records:
                print(
                    f"[Three.js Export] Temporarily skipped "
                    f"{len(quarantine_records)} unsupported F-curve(s)."
                )
                for _collection, _copy, action_name, path, index in \
                        quarantine_records[:10]:
                    print(
                        f"  - {action_name}: {path}[{index}]"
                    )

            _export_glb(
                staging_path, character_objects,
                animations=True, frame_step=frame_step,
            )
            animation_document, animation_binary = _read_glb(staging_path)
            animation_data = _extract_animation_data(
                animation_document, animation_binary,
                wanted_names, effective_fps,
            )

        exported_names = {animation["name"] for animation in animation_data}
        missing = sorted(wanted_names - exported_names, key=str.casefold)
        if missing:
            raise RuntimeError(
                "Blender did not emit these character Actions: "
                + ", ".join(missing)
            )

        _remove_old_generated_animation_files(animation_dir)
        named_animations = _unique_names(animation_data)
        for animation, identifier, filename in named_animations:
            filepath = os.path.join(animation_dir, filename + ".ts")
            _atomic_write(filepath, _animation_module(animation, identifier))
            generated_files.append(filepath)

        _atomic_write(index_path, _index_module(named_animations))
        _atomic_write(factory_path, _factory_module())
        generated_files.extend([index_path, factory_path])

        track_count = sum(
            len(animation["tracks"]) for animation in animation_data
        )
        keyframe_count = sum(
            len(track["times"])
            for animation in animation_data
            for track in animation["tracks"]
        )

        print("\n" + "=" * 72)
        print("THREE.JS CHARACTER EXPORT COMPLETE")
        print("=" * 72)
        print(f"Character GLB: {glb_path}")
        print(f"Armature: {armature.name}")
        print(f"Animations: {len(animation_data)}")
        for animation in animation_data:
            keys = sum(len(track["times"]) for track in animation["tracks"])
            print(
                f"  - {animation['name']}: "
                f"{len(animation['tracks'])} tracks, {keys} keyframes, "
                f"{animation['duration']}s"
            )
        print(f"Total tracks: {track_count}")
        print(f"Total keyframes: {keyframe_count}")
        print(f"Sampling FPS: {effective_fps:g} (frame step {frame_step})")
        print("Generated files:")
        for filepath in generated_files:
            print(
                f"  {filepath} — {_human_size(os.path.getsize(filepath))}"
            )
        print("=" * 72)

        return {
            "character_glb": glb_path,
            "animations": animation_data,
            "tracks": track_count,
            "keyframes": keyframe_count,
            "files": generated_files,
        }
    finally:
        if quarantine:
            try:
                _restore_quarantined_fcurves(
                    quarantine, quarantine_records
                )
            except Exception:
                print(
                    "[Three.js Export] ERROR restoring quarantined F-curves. "
                    "They remain preserved in __TJS_EXPORT_QUARANTINE__."
                )
                traceback.print_exc()
        if os.path.isfile(staging_path):
            try:
                os.remove(staging_path)
            except OSError:
                pass
        _restore_scene_state(state)


if __name__ == "__main__":
    try:
        export_character_and_animations()
    except Exception:
        print("[Three.js Export] FAILED")
        traceback.print_exc()
        raise
