"""
TypeScript module generation for the decoupled T3AN animation format.

Generated files intentionally contain URLs and metadata, while the sampled
track payload stays in the compact ``.anim`` files.  This keeps the helper
modules useful without duplicating the binary data in source control.
"""

import json
import os
import re


GENERATED_MARKER = "// Generated by Blender Three.js Character Exporter"
WINDOWS_RESERVED = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}
TS_RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger",
    "default", "delete", "do", "else", "enum", "export", "extends",
    "false", "finally", "for", "function", "if", "implements", "import",
    "in", "instanceof", "interface", "let", "new", "null", "package",
    "private", "protected", "public", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "var", "void",
    "while", "with", "yield",
}


def safe_identifier(name):
    identifier = re.sub(r"\W+", "_", str(name), flags=re.UNICODE).strip("_")
    if not identifier:
        identifier = "Animation"
    if identifier[0].isdigit() or identifier in TS_RESERVED:
        identifier = f"Animation_{identifier}"
    return identifier


def safe_filename(name):
    filename = re.sub(r'[<>:"/\\|?*#%\x00-\x1F]+', "_", str(name)).strip(" .")
    if not filename:
        filename = "Animation"
    if filename.upper() in WINDOWS_RESERVED:
        filename = f"Animation_{filename}"
    return filename


def _atomic_write(filepath, content):
    temporary = filepath + ".tmp"
    with open(temporary, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, filepath)


def _json(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _unique_asset_names(assets):
    used = set()
    result = []
    for asset in assets:
        base = safe_identifier(asset["name"])
        identifier = base
        suffix = 2
        while identifier.casefold() in used:
            identifier = f"{base}_{suffix}"
            suffix += 1
        used.add(identifier.casefold())
        result.append((asset, identifier))
    return result


def _animation_module(asset, identifier):
    """Generate one typed descriptor for a compact binary animation."""
    asset_url = "./" + asset["file"].split("/")[-1]
    content_hash = str(asset.get("contentHash", "")).lower()
    if content_hash:
        asset_url += "?v=" + content_hash
    metadata = {
        "name": asset["name"],
        "duration": asset.get("duration", 0.0),
        "fps": asset.get("fps", 30.0),
        "tracks": asset.get("tracks", 0),
        "keyframes": asset.get("keyframes", 0),
        "size": asset.get("size", 0),
        "contentHash": asset.get("contentHash", ""),
    }
    return (
        f"{GENERATED_MARKER}\n"
        'import type { AnimationAsset } from "../animationClipFactory.js";\n\n'
        f"export const {identifier} = {{\n"
        f"  ...{_json(metadata)},\n"
        f"  url: new URL({_json(asset_url)}, import.meta.url).href,\n"
        "} as const satisfies AnimationAsset;\n"
        f"export default {identifier};\n"
    )


def _index_module(named_assets):
    if not named_assets:
        return (
            f"{GENERATED_MARKER}\n"
            'import type { AnimationAsset } from "../animationClipFactory.js";\n\n'
            "export const animations = [] as const satisfies readonly AnimationAsset[];\n"
            "export const animationNames = [] as const;\n"
            "export const animationByName = new Map<string, AnimationAsset>();\n"
            "export type AnimationName = never;\n"
        )

    imports = "\n".join(
        f'import {{ {identifier} }} from "./{asset["file"].split("/")[-1].rsplit(".", 1)[0]}.js";'
        for asset, identifier in named_assets
    )
    identifiers = ", ".join(identifier for _asset, identifier in named_assets)
    return (
        f"{GENERATED_MARKER}\n"
        'import type { AnimationAsset } from "../animationClipFactory.js";\n'
        f"{imports}\n\n"
        f"export {{ {identifiers} }};\n"
        f"export const animations = [{identifiers}] as const;\n"
        "export const animationNames = animations.map((asset) => asset.name) as readonly string[];\n"
        "export const animationByName = new Map<string, AnimationAsset>(animations.map((asset) => [asset.name, asset] as const));\n"
        'export type AnimationName = (typeof animations)[number]["name"];\n'
    )


def _factory_module():
    return f'''{GENERATED_MARKER}
import * as THREE from "three";

export type AnimationProperty = "position" | "quaternion" | "scale" | `morphTargetInfluences[${{number}}]`;

export interface AnimationAsset {{
  readonly name: string;
  readonly url: string;
  readonly duration: number;
  readonly fps: number;
  readonly tracks: number;
  readonly keyframes: number;
  readonly size: number;
  readonly contentHash?: string;
}}

export interface AnimationManifestEntry {{
  readonly file: string;
  readonly duration: number;
  readonly fps: number;
  readonly tracks: number;
  readonly keyframes: number;
  readonly size: number;
  readonly contentHash?: string;
  readonly module?: string;
}}

export interface AnimationManifestTarget {{
  readonly name: string;
  readonly kind: "bone" | "object";
}}

export interface AnimationManifest {{
  readonly version: number;
  readonly format: string;
  readonly character: string;
  readonly characterHash?: string;
  readonly characterSize?: number;
  readonly mappingHash: number;
  readonly skeleton: readonly string[];
  readonly objects: readonly string[];
  readonly targets?: readonly AnimationManifestTarget[];
  readonly animations: Readonly<Record<string, AnimationManifestEntry>>;
}}

const MAGIC = "T3AN";
const HEADER_SIZE = 32;
const TRACK_HEADER_SIZE = 16;

function align4(value: number): number {{
  return (value + 3) & ~3;
}}

function fail(message: string): never {{
  throw new Error(`Invalid T3AN animation: ${{message}}`);
}}

function readMagic(view: DataView): string {{
  return String.fromCharCode(
    view.getUint8(0),
    view.getUint8(1),
    view.getUint8(2),
    view.getUint8(3),
  );
}}

function targetNames(manifest: AnimationManifest): readonly string[] {{
  if (manifest.targets?.length) return manifest.targets.map((target) => target.name);
  return [...manifest.skeleton, ...manifest.objects];
}}

function normalizeQuaternion(values: number[]): void {{
  const length = Math.hypot(...values);
  if (length <= 1e-12) {{
    values[0] = 0;
    values[1] = 0;
    values[2] = 0;
    values[3] = 1;
    return;
  }}
  for (let index = 0; index < values.length; index += 1) values[index] /= length;
}}

function createTrack(
  binding: string,
  property: AnimationProperty,
  times: number[],
  values: number[],
  interpolation: number,
): THREE.KeyframeTrack {{
  let track: THREE.KeyframeTrack;
  if (property === "quaternion") track = new THREE.QuaternionKeyframeTrack(binding, times, values);
  else if (property === "position" || property === "scale") track = new THREE.VectorKeyframeTrack(binding, times, values);
  else track = new THREE.NumberKeyframeTrack(binding, times, values);
  if (interpolation === 1) track.setInterpolation(THREE.InterpolateDiscrete);
  return track;
}}

export function parseAnimationClip(
  buffer: ArrayBuffer,
  asset: Pick<AnimationAsset, "name" | "duration" | "fps" | "contentHash">,
  manifest: AnimationManifest,
): THREE.AnimationClip {{
  if (buffer.byteLength < HEADER_SIZE) fail("file is shorter than its header");
  const view = new DataView(buffer);
  if (readMagic(view) !== MAGIC) fail("magic does not match T3AN");
  const version = view.getUint16(4, true);
  const headerSize = view.getUint16(6, true);
  if (version !== 1 || headerSize !== HEADER_SIZE) fail("unsupported version or header");
  const duration = view.getFloat32(8, true);
  const fps = view.getFloat32(12, true);
  const trackCount = view.getUint16(16, true);
  const mappingHash = view.getUint32(24, true);
  const fileSize = view.getUint32(28, true);
  if (fileSize !== buffer.byteLength) fail("file size field is incorrect");
  if ((mappingHash >>> 0) !== (manifest.mappingHash >>> 0)) fail("target mapping differs from the manifest");
  if (!Number.isFinite(fps) || fps <= 0) fail("invalid sampling rate");

  const targets = targetNames(manifest);
  const tracks: THREE.KeyframeTrack[] = [];
  let offset = headerSize;
  for (let trackIndex = 0; trackIndex < trackCount; trackIndex += 1) {{
    if (offset + TRACK_HEADER_SIZE > buffer.byteLength) fail("truncated track header");
    const targetId = view.getUint16(offset, true);
    const propertyCode = view.getUint8(offset + 2);
    const interpolation = view.getUint8(offset + 3);
    const encoding = view.getUint8(offset + 4);
    const timeMode = view.getUint8(offset + 5);
    const componentCount = view.getUint8(offset + 6);
    const morphIndex = view.getUint16(offset + 8, true);
    const keyCount = view.getUint32(offset + 12, true);
    offset += TRACK_HEADER_SIZE;
    if (targetId >= targets.length || keyCount === 0) fail("invalid target or key count");

    const times: number[] = [];
    if (timeMode === 0) {{
      if (offset + 8 > buffer.byteLength) fail("truncated uniform time payload");
      const start = view.getUint32(offset, true);
      const step = view.getUint32(offset + 4, true);
      offset += 8;
      for (let index = 0; index < keyCount; index += 1) times.push((start + step * index) / fps);
    }} else if (timeMode === 1) {{
      if (offset + keyCount * 2 > buffer.byteLength) fail("truncated uint16 times");
      for (let index = 0; index < keyCount; index += 1) times.push(view.getUint16(offset + index * 2, true) / fps);
      offset += keyCount * 2;
    }} else if (timeMode === 2) {{
      if (offset + keyCount * 4 > buffer.byteLength) fail("truncated uint32 times");
      for (let index = 0; index < keyCount; index += 1) times.push(view.getUint32(offset + index * 4, true) / fps);
      offset += keyCount * 4;
    }} else if (timeMode === 3) {{
      if (offset + keyCount * 4 > buffer.byteLength) fail("truncated float times");
      for (let index = 0; index < keyCount; index += 1) times.push(view.getFloat32(offset + index * 4, true));
      offset += keyCount * 4;
    }} else fail("unknown time encoding");
    offset = align4(offset);

    const values: number[] = [];
    if (encoding === 0) {{
      const byteCount = keyCount * componentCount * 4;
      if (offset + byteCount > buffer.byteLength) fail("truncated float values");
      for (let index = 0; index < keyCount * componentCount; index += 1) values.push(view.getFloat32(offset + index * 4, true));
      offset += byteCount;
    }} else if (encoding === 1) {{
      if (componentCount !== 4) fail("quaternion encoding has the wrong width");
      const byteCount = keyCount * componentCount * 2;
      if (offset + byteCount > buffer.byteLength) fail("truncated quaternion values");
      for (let key = 0; key < keyCount; key += 1) {{
        const row: number[] = [];
        for (let component = 0; component < componentCount; component += 1) row.push(view.getInt16(offset + (key * componentCount + component) * 2, true) / 32767);
        normalizeQuaternion(row);
        values.push(...row);
      }}
      offset += byteCount;
    }} else if (encoding === 2 || encoding === 3) {{
      const width = componentCount;
      const rangeBytes = width * 8;
      if (offset + rangeBytes > buffer.byteLength) fail("truncated quantization range");
      const minimum: number[] = [];
      const maximum: number[] = [];
      for (let component = 0; component < width; component += 1) minimum.push(view.getFloat32(offset + component * 4, true));
      for (let component = 0; component < width; component += 1) maximum.push(view.getFloat32(offset + width * 4 + component * 4, true));
      offset += rangeBytes;
      const valueBytes = keyCount * width * 2;
      if (offset + valueBytes > buffer.byteLength) fail("truncated quantized values");
      for (let key = 0; key < keyCount; key += 1) {{
        for (let component = 0; component < width; component += 1) {{
          const quantized = view.getUint16(offset + (key * width + component) * 2, true) / 65535;
          values.push(minimum[component] + quantized * (maximum[component] - minimum[component]));
        }}
      }}
      offset += valueBytes;
    }} else fail("unknown value encoding");
    offset = align4(offset);

    let property: AnimationProperty;
    if (propertyCode === 0) property = "position";
    else if (propertyCode === 1) property = "quaternion";
    else if (propertyCode === 2) property = "scale";
    else if (propertyCode === 3) property = `morphTargetInfluences[${{morphIndex}}]`;
    else fail("unknown track property");
    const target = targets[targetId];
    tracks.push(createTrack(`${{target}}.${{property}}`, property, times, values, interpolation));
  }}

  const clipDuration = Number.isFinite(duration) ? duration : asset.duration;
  return new THREE.AnimationClip(asset.name, clipDuration, tracks);
}}

export async function loadAnimationManifest(url: string, signal?: AbortSignal): Promise<AnimationManifest> {{
  const response = await fetch(url, {{ signal, cache: "no-store" }});
  if (!response.ok) throw new Error(`Could not load animation manifest (${{response.status}})`);
  const manifest = await response.json() as AnimationManifest;
  if (manifest.format !== MAGIC || manifest.version !== 1) throw new Error("Unsupported animation manifest format");
  if (!manifest.character || !manifest.animations || !Number.isFinite(manifest.mappingHash)) throw new Error("Animation manifest is incomplete");
  return manifest;
}}

export function fnv1a32(bytes: ArrayBuffer): string {{
  const data = new Uint8Array(bytes);
  let value = 0x811c9dc5;
  for (const byte of data) value = Math.imul(value ^ byte, 0x01000193) >>> 0;
  return value.toString(16).padStart(8, "0");
}}

export async function loadAnimationClip(
  asset: AnimationAsset,
  manifest: AnimationManifest,
  options: {{ signal?: AbortSignal; verifyHash?: boolean }} = {{}},
): Promise<THREE.AnimationClip> {{
  const response = await fetch(asset.url, {{ signal: options.signal }});
  if (!response.ok) throw new Error(`Could not load animation "${{asset.name}}" (${{response.status}})`);
  const buffer = await response.arrayBuffer();
  if (asset.size > 0 && buffer.byteLength !== asset.size) throw new Error(`Animation size mismatch for "${{asset.name}}"`);
  if (options.verifyHash !== false && asset.contentHash && fnv1a32(buffer) !== asset.contentHash.toLowerCase()) throw new Error(`Animation hash mismatch for "${{asset.name}}"`);
  return parseAnimationClip(buffer, asset, manifest);
}}
'''


def _model_controller_module(glb_filename):
    del glb_filename
    return f'''{GENERATED_MARKER}
import * as THREE from "three";
import {{ GLTFLoader, type GLTF }} from "three/addons/loaders/GLTFLoader.js";
import type {{ AnimationName }} from "./animations/index.js";
import {{
  fnv1a32,
  loadAnimationClip,
  loadAnimationManifest,
  type AnimationAsset,
  type AnimationManifest,
}} from "./animationClipFactory.js";

export const manifestUrl = new URL("./animation-manifest.json", import.meta.url).href;
export type {{ AnimationName }};

export interface LoadAnimatedModelOptions {{
  manager?: THREE.LoadingManager;
  dracoLoader?: Parameters<GLTFLoader["setDRACOLoader"]>[0];
  meshoptDecoder?: Parameters<GLTFLoader["setMeshoptDecoder"]>[0];
  preloadAnimations?: boolean | readonly (AnimationName | (string & {{}}))[];
  verifyCharacterHash?: boolean;
  verifyAnimationHashes?: boolean;
  crossFadeDuration?: number;
}}

export interface PlayOptions {{
  fade?: number;
  loop?: typeof THREE.LoopOnce | typeof THREE.LoopRepeat | typeof THREE.LoopPingPong;
  repetitions?: number;
  clampWhenFinished?: boolean;
  timeScale?: number;
}}

export interface AnimatedModelController {{
  gltf: GLTF;
  manifest: AnimationManifest;
  root: THREE.Group;
  mixer: THREE.AnimationMixer;
  clips: ReadonlyMap<string, THREE.AnimationClip>;
  animationNames: readonly string[];
  loadClip(name: AnimationName | (string & {{}})): Promise<THREE.AnimationClip>;
  preload(names?: readonly (AnimationName | (string & {{}}))[]): Promise<void>;
  getAction(name: AnimationName | (string & {{}})): THREE.AnimationAction;
  play(name: AnimationName | (string & {{}}), options?: PlayOptions): Promise<THREE.AnimationAction>;
  stop(fade?: number): void;
  update(deltaSeconds: number): void;
  dispose(): void;
}}

export async function loadAnimatedModel(
  options: LoadAnimatedModelOptions = {{}},
): Promise<AnimatedModelController> {{
  const {{
    manager,
    dracoLoader,
    meshoptDecoder,
    preloadAnimations = false,
    verifyCharacterHash = true,
    verifyAnimationHashes = true,
    crossFadeDuration = 0.25,
  }} = options;
  const loader = new GLTFLoader(manager);
  if (dracoLoader) loader.setDRACOLoader(dracoLoader);
  if (meshoptDecoder) loader.setMeshoptDecoder(meshoptDecoder);

  const manifest = await loadAnimationManifest(manifestUrl);
  const versionedUrl = (relative: string, hash?: string): string => {{
    const url = new URL(relative, manifestUrl);
    if (hash) url.searchParams.set("v", hash.toLowerCase());
    return url.href;
  }};
  const resolvedModelUrl = versionedUrl(manifest.character, manifest.characterHash);
  const modelResponse = await fetch(resolvedModelUrl);
  if (!modelResponse.ok) throw new Error(`Could not load character model (${{modelResponse.status}})`);
  const modelBuffer = await modelResponse.arrayBuffer();
  if (manifest.characterSize && modelBuffer.byteLength !== manifest.characterSize) throw new Error("Character model size does not match the manifest");
  if (verifyCharacterHash && manifest.characterHash && fnv1a32(modelBuffer) !== manifest.characterHash.toLowerCase()) throw new Error("Character model hash does not match the manifest");
  const gltf = await loader.parseAsync(modelBuffer, new URL("./", resolvedModelUrl).href);
  const root = gltf.scene;
  const mixer = new THREE.AnimationMixer(root);
  const clips = new Map<string, THREE.AnimationClip>();
  const pending = new Map<string, Promise<THREE.AnimationClip>>();
  const actions = new Map<string, THREE.AnimationAction>();
  let currentAction: THREE.AnimationAction | null = null;
  let disposed = false;
  const runtimeAnimationNames = Object.freeze(Object.keys(manifest.animations));

  function manifestAsset(name: string): AnimationAsset {{
    const entry = manifest.animations[name];
    if (!entry) throw new Error(`Unknown animation "${{name}}". Available: ${{runtimeAnimationNames.join(", ") || "none"}}`);
    return {{
      name,
      url: versionedUrl(entry.file, entry.contentHash),
      duration: entry.duration,
      fps: entry.fps,
      tracks: entry.tracks,
      keyframes: entry.keyframes,
      size: entry.size,
      contentHash: entry.contentHash,
    }};
  }}

  async function loadClip(name: AnimationName | (string & {{}})): Promise<THREE.AnimationClip> {{
    if (disposed) throw new Error("Animated model has been disposed");
    const key = String(name);
    const cached = clips.get(key);
    if (cached) return cached;
    const inFlight = pending.get(key);
    if (inFlight) return inFlight;
    const asset = manifestAsset(key);
    const request = loadAnimationClip(asset, manifest, {{ verifyHash: verifyAnimationHashes }})
      .then((clip) => {{ clips.set(key, clip); return clip; }})
      .finally(() => pending.delete(key));
    pending.set(key, request);
    return request;
  }}

  async function preload(names = runtimeAnimationNames): Promise<void> {{
    await Promise.all(names.map((name) => loadClip(name)));
  }}

  function getAction(name: AnimationName | (string & {{}})): THREE.AnimationAction {{
    const key = String(name);
    const clip = clips.get(key);
    if (!clip) throw new Error(`Animation "${{key}}" is not loaded; call loadClip() or play() first`);
    const action = actions.get(key) ?? mixer.clipAction(clip);
    actions.set(key, action);
    return action;
  }}

  async function play(
    name: AnimationName | (string & {{}}),
    playOptions: PlayOptions = {{}},
  ): Promise<THREE.AnimationAction> {{
    const clip = await loadClip(name);
    const key = clip.name;
    const {{
      fade = crossFadeDuration,
      loop = THREE.LoopRepeat,
      repetitions = Infinity,
      clampWhenFinished = false,
      timeScale = 1,
    }} = playOptions;
    const nextAction = getAction(key);
    nextAction.enabled = true;
    nextAction.clampWhenFinished = clampWhenFinished;
    nextAction.setLoop(loop, repetitions);
    nextAction.setEffectiveTimeScale(timeScale);
    nextAction.setEffectiveWeight(1);
    if (currentAction && currentAction !== nextAction) currentAction.fadeOut(fade);
    nextAction.reset().fadeIn(fade).play();
    currentAction = nextAction;
    return nextAction;
  }}

  function stop(fade = crossFadeDuration): void {{
    if (!currentAction) return;
    if (fade > 0) currentAction.fadeOut(fade);
    else currentAction.stop();
    currentAction = null;
  }}

  function update(deltaSeconds: number): void {{ mixer.update(deltaSeconds); }}

  function dispose(): void {{
    if (disposed) return;
    disposed = true;
    stop(0);
    mixer.stopAllAction();
    mixer.uncacheRoot(root);
    root.traverse((object) => {{
      if (!(object instanceof THREE.Mesh)) return;
      object.geometry.dispose();
      const materials: THREE.Material[] = Array.isArray(object.material) ? object.material : [object.material];
      for (const material of materials) {{
        if (!material) continue;
        for (const value of Object.values(material)) if (value instanceof THREE.Texture) value.dispose();
        material.dispose();
      }}
    }});
    clips.clear();
    actions.clear();
  }}

  const controller: AnimatedModelController = {{
    gltf, manifest, root, mixer, clips,
    animationNames: runtimeAnimationNames,
    loadClip, preload, getAction, play, stop, update, dispose,
  }};
  if (preloadAnimations === true) await preload();
  else if (Array.isArray(preloadAnimations)) await preload(preloadAnimations);
  return controller;
}}
'''


def typescript_module(glb_filename, animation_names=None):
    """Backward-compatible entry point for callers that only need the loader."""
    del animation_names
    return _model_controller_module(glb_filename)


def write_typescript_modules(output_dir, glb_filename, assets):
    """Write the factory, controller, per-animation, and index modules."""
    animation_dir = os.path.join(output_dir, "animations")
    os.makedirs(animation_dir, exist_ok=True)
    named_assets = _unique_asset_names(assets)
    generated = []

    factory_path = os.path.join(output_dir, "animationClipFactory.ts")
    controller_path = os.path.join(output_dir, "model_controller.ts")
    _atomic_write(factory_path, _factory_module())
    _atomic_write(controller_path, _model_controller_module(glb_filename))
    generated.extend([factory_path, controller_path])

    for asset, identifier in named_assets:
        stem = os.path.splitext(os.path.basename(asset["file"]))[0]
        filepath = os.path.join(animation_dir, stem + ".ts")
        _atomic_write(filepath, _animation_module(asset, identifier))
        generated.append(filepath)

    index_path = os.path.join(animation_dir, "index.ts")
    _atomic_write(index_path, _index_module(named_assets))
    generated.append(index_path)
    return generated


__all__ = [
    "GENERATED_MARKER",
    "safe_filename",
    "safe_identifier",
    "typescript_module",
    "write_typescript_modules",
]
