"""
Blender 5.1+ character and compact binary animation exporter.

Final output:
    character.glb
    animation-manifest.json
    animations/
        ActionName.anim

Run this file from Blender's Text Editor. The final GLB never contains
animation clips. Animation values are extracted from a temporary sampled GLB
so they exactly match Blender's glTF coordinate/bone conversion.
"""

import bpy
import json
import math
import os
import re
import struct
import traceback


# ============================================================================
# Configuration
# ============================================================================

# Set this to False when exporting somewhere other than the linked portfolio.
USE_PORTFOLIO_ONE_CLICK_DEFAULTS = True
PORTFOLIO_OUTPUT_DIRECTORY = r"C:\Users\rocky\OneDrive\Documents\GitHub\portfolio\public\models"
OUTPUT_DIRECTORY = PORTFOLIO_OUTPUT_DIRECTORY if USE_PORTFOLIO_ONE_CLICK_DEFAULTS else "//threejs_character/"
GLB_FILENAME = "character.glb"
EXPORT_ALL_ACTIONS = True
ACTIONS_TO_EXCLUDE = {
    # "T-Pose",
}
DECIMAL_PRECISION = 5
SAMPLING_FPS = 30
SAMPLE_BAKED_ANIMATION = True
APPLY_MODIFIERS = False
EXPORT_MATERIALS = True
EXPORT_TEXTURES = True
TEXTURE_IMAGE_FORMAT = "AUTO"  # AUTO, JPEG, WEBP, or NONE
TEXTURE_QUALITY = 85
EXPORT_MORPH_TARGETS = True
EXPORT_VERTEX_COLORS = True
EXPORT_TANGENTS = False
EXPORT_CUSTOM_PROPERTIES = False
MESH_COMPRESSION = "NONE"  # NONE or DRACO
DRACO_COMPRESSION_LEVEL = 6
DRACO_POSITION_QUANTIZATION = 14
DRACO_NORMAL_QUANTIZATION = 10
DRACO_TEXCOORD_QUANTIZATION = 12
DRACO_COLOR_QUANTIZATION = 10
DRACO_GENERIC_QUANTIZATION = 12

# Animation optimization. Distances use exported glTF units; rotation is degrees.
POSITION_TOLERANCE = 0.0001
ROTATION_TOLERANCE_DEGREES = 0.05
SCALE_TOLERANCE = 0.0001
MORPH_TOLERANCE = 0.0005
ENABLE_KEYFRAME_REDUCTION = True
REMOVE_STATIC_TRACKS = True
ENABLE_QUANTIZATION = True
QUANTIZE_QUATERNIONS = True
QUANTIZE_POSITIONS = True
QUANTIZE_SCALES = True
QUANTIZE_MORPHS = True
MANIFEST_FILENAME = "animation-manifest.json"
PROGRESS_CALLBACK = None


# ============================================================================
# Constants
# ============================================================================

_GENERATED_MARKER = "// Generated by Blender Three.js Character Exporter"
_STAGING_FILENAME = ".__threejs_animation_staging__.glb"
_TRANSFORM_WIDTHS = {
    "delta_location": 3,
    "delta_rotation_euler": 3,
    "delta_rotation_quaternion": 4,
    "delta_scale": 3,
    "location": 3,
    "rotation_axis_angle": 4,
    "rotation_euler": 3,
    "rotation_quaternion": 4,
    "scale": 3,
    "value": 1,
}
_COMPONENT_FORMATS = {
    5120: "b",
    5121: "B",
    5122: "h",
    5123: "H",
    5125: "I",
    5126: "f",
}
_ACCESSOR_WIDTHS = {
    "SCALAR": 1,
    "VEC2": 2,
    "VEC3": 3,
    "VEC4": 4,
    "MAT2": 4,
    "MAT3": 9,
    "MAT4": 16,
}
_TS_RESERVED = {
    "break", "case", "catch", "class", "const", "continue", "debugger",
    "default", "delete", "do", "else", "enum", "export", "extends",
    "false", "finally", "for", "function", "if", "implements", "import",
    "in", "instanceof", "interface", "let", "new", "null", "package",
    "private", "protected", "public", "return", "static", "super",
    "switch", "this", "throw", "true", "try", "typeof", "var", "void",
    "while", "with", "yield",
}
_WINDOWS_RESERVED = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}


# ============================================================================
# Scene and Action discovery
# ============================================================================

def _skinned_meshes_for_armature(armature):
    meshes = []
    for obj in bpy.context.scene.objects:
        if obj.type != "MESH":
            continue
        uses_armature = any(
            modifier.type == "ARMATURE" and modifier.object == armature
            for modifier in obj.modifiers
        )
        parented_to_armature = (
            obj.parent == armature and obj.parent_type in {"ARMATURE", "BONE"}
        )
        if uses_armature or parented_to_armature:
            meshes.append(obj)
    return sorted(meshes, key=lambda obj: obj.name)


def _find_primary_armature():
    candidates = []
    for armature in (obj for obj in bpy.context.scene.objects
                     if obj.type == "ARMATURE"):
        meshes = _skinned_meshes_for_armature(armature)
        vertex_count = sum(len(mesh.data.vertices) for mesh in meshes)
        candidates.append((len(meshes), vertex_count, armature.name,
                           armature, meshes))

    if not candidates:
        raise RuntimeError("No Armature exists in the current scene.")

    candidates.sort(key=lambda item: (item[0], item[1], item[2]), reverse=True)
    mesh_count, _vertices, _name, armature, meshes = candidates[0]
    if mesh_count == 0:
        raise RuntimeError(
            f"Found Armature '{armature.name}', but no meshes are skinned to it."
        )
    return armature, meshes


def _collect_character_objects(armature, meshes):
    result = {armature, *meshes}
    pending = list(result)
    while pending:
        obj = pending.pop()
        if obj.parent and obj.parent not in result:
            result.add(obj.parent)
            pending.append(obj.parent)
    return sorted(result, key=lambda obj: obj.name)


def _iter_action_fcurve_collections(action):
    found_slotted = False
    for layer in getattr(action, "layers", []):
        for strip in layer.strips:
            for channelbag in getattr(strip, "channelbags", []):
                found_slotted = True
                yield channelbag.fcurves
    if found_slotted:
        return
    try:
        yield action.fcurves
    except (AttributeError, RuntimeError):
        pass


def _iter_action_fcurves(action):
    for collection in _iter_action_fcurve_collections(action):
        yield from collection


def _action_has_keyframes(action):
    return any(
        len(fcurve.keyframe_points) > 0 or len(fcurve.sampled_points) > 0
        for fcurve in _iter_action_fcurves(action)
    )


def _actions_used_by_id(data_block):
    result = set()
    animation_data = getattr(data_block, "animation_data", None)
    if not animation_data:
        return result
    if animation_data.action:
        result.add(animation_data.action)
    for track in animation_data.nla_tracks:
        for strip in track.strips:
            if strip.action:
                result.add(strip.action)
    return result


def _find_character_actions(armature, meshes):
    used = _actions_used_by_id(armature)
    shape_key_names = set()
    for mesh in meshes:
        used.update(_actions_used_by_id(mesh))
        shape_keys = mesh.data.shape_keys
        if shape_keys and EXPORT_MORPH_TARGETS:
            used.update(_actions_used_by_id(shape_keys))
            shape_key_names.update(key.name for key in shape_keys.key_blocks)

    actions = set(used)
    if EXPORT_ALL_ACTIONS:
        bone_names = set(armature.data.bones.keys())
        bone_pattern = re.compile(r'pose\.bones\["((?:\\.|[^"])*)"\]')
        shape_pattern = re.compile(r'key_blocks\["((?:\\.|[^"])*)"\]\.value')
        for action in bpy.data.actions:
            for fcurve in _iter_action_fcurves(action):
                bone_match = bone_pattern.search(fcurve.data_path)
                if bone_match and bone_match.group(1) in bone_names:
                    actions.add(action)
                    break
                shape_match = shape_pattern.search(fcurve.data_path)
                if shape_match and shape_match.group(1) in shape_key_names:
                    actions.add(action)
                    break

    excluded = {name.casefold() for name in ACTIONS_TO_EXCLUDE}
    return sorted(
        (action for action in actions
         if action.name.casefold() not in excluded
         and _action_has_keyframes(action)),
        key=lambda action: action.name.casefold(),
    )


# ============================================================================
# Reversible workaround for malformed Blender/glTF F-curves
# ============================================================================

def _is_unsafe_fcurve(fcurve):
    target = fcurve.data_path.rsplit(".", 1)[-1]
    if target.startswith("["):
        target = ""
    target_width = _TRANSFORM_WIDTHS.get(target, 1)
    return fcurve.array_index < 0 or fcurve.array_index >= target_width


def _quarantine_unsafe_fcurves():
    quarantine = bpy.data.actions.new("__TJS_EXPORT_QUARANTINE__")
    slot = quarantine.slots.new("SCENE", "TJS Export Quarantine")
    layer = quarantine.layers.new("Quarantine")
    strip = layer.strips.new(type="KEYFRAME")
    destination = strip.channelbags.new(slot).fcurves
    records = []

    for action in list(bpy.data.actions):
        if action == quarantine:
            continue
        for collection in _iter_action_fcurve_collections(action):
            for fcurve in list(collection):
                if not _is_unsafe_fcurve(fcurve):
                    continue
                copy = destination.new_from_fcurve(fcurve)
                records.append((collection, copy, action.name,
                                fcurve.data_path, fcurve.array_index))
                collection.remove(fcurve)
    return quarantine, records


def _restore_quarantined_fcurves(quarantine, records):
    for collection, copy, _action_name, _path, _index in records:
        collection.new_from_fcurve(copy)
    if quarantine:
        bpy.data.actions.remove(quarantine)


# ============================================================================
# GLB export and parsing
# ============================================================================

def _export_glb(filepath, objects, *, animations, frame_step=1):
    bpy.ops.object.mode_set(mode="OBJECT") if bpy.context.object and \
        bpy.context.object.mode != "OBJECT" else None
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.hide_set(False)
        obj.hide_viewport = False
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]

    image_format = (
        TEXTURE_IMAGE_FORMAT
        if EXPORT_MATERIALS and EXPORT_TEXTURES
        else "NONE"
    )
    use_draco = MESH_COMPRESSION == "DRACO" and not animations
    options = dict(
        filepath=filepath,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=APPLY_MODIFIERS,
        export_materials="EXPORT" if EXPORT_MATERIALS else "NONE",
        export_image_format=image_format,
        export_jpeg_quality=TEXTURE_QUALITY,
        export_image_quality=TEXTURE_QUALITY,
        export_vertex_color="MATERIAL" if EXPORT_VERTEX_COLORS else "NONE",
        export_all_vertex_colors=EXPORT_VERTEX_COLORS,
        export_tangents=EXPORT_TANGENTS,
        export_extras=EXPORT_CUSTOM_PROPERTIES,
        export_draco_mesh_compression_enable=use_draco,
        export_draco_mesh_compression_level=DRACO_COMPRESSION_LEVEL,
        export_draco_position_quantization=DRACO_POSITION_QUANTIZATION,
        export_draco_normal_quantization=DRACO_NORMAL_QUANTIZATION,
        export_draco_texcoord_quantization=DRACO_TEXCOORD_QUANTIZATION,
        export_draco_color_quantization=DRACO_COLOR_QUANTIZATION,
        export_draco_generic_quantization=DRACO_GENERIC_QUANTIZATION,
        export_skins=True,
        export_def_bones=False,
        export_rest_position_armature=True,
        export_leaf_bone=False,
        export_morph=EXPORT_MORPH_TARGETS,
        export_animations=animations,
    )
    if animations:
        options.update(
            export_animation_mode="ACTIONS",
            export_merge_animation="ACTION",
            export_force_sampling=SAMPLE_BAKED_ANIMATION,
            export_frame_step=frame_step,
            export_optimize_animation_size=True,
            export_optimize_animation_keep_anim_armature=True,
            export_anim_single_armature=True,
            export_anim_slide_to_zero=True,
            export_morph_animation=EXPORT_MORPH_TARGETS,
            export_extra_animations=False,
        )
    else:
        options.update(export_morph_animation=False)

    result = bpy.ops.export_scene.gltf(**options)
    if "FINISHED" not in result:
        raise RuntimeError(f"Blender cancelled GLB export: {filepath}")


def _read_glb(filepath):
    with open(filepath, "rb") as handle:
        header = handle.read(12)
        if len(header) != 12:
            raise ValueError(f"Invalid GLB header: {filepath}")
        magic, version, total_length = struct.unpack("<4sII", header)
        if magic != b"glTF" or version != 2:
            raise ValueError(f"Not a glTF 2.0 GLB: {filepath}")

        document = None
        binary = b""
        while handle.tell() < total_length:
            chunk_header = handle.read(8)
            if len(chunk_header) != 8:
                raise ValueError("Truncated GLB chunk header.")
            chunk_length, chunk_type = struct.unpack("<II", chunk_header)
            chunk = handle.read(chunk_length)
            if len(chunk) != chunk_length:
                raise ValueError("Truncated GLB chunk.")
            if chunk_type == 0x4E4F534A:
                document = json.loads(
                    chunk.rstrip(b"\x00 \t\r\n").decode("utf-8")
                )
            elif chunk_type == 0x004E4942:
                binary = chunk

    if document is None:
        raise ValueError("GLB contains no JSON document.")
    return document, binary


def _normalize_component(value, component_type):
    if component_type == 5120:
        return max(value / 127.0, -1.0)
    if component_type == 5121:
        return value / 255.0
    if component_type == 5122:
        return max(value / 32767.0, -1.0)
    if component_type == 5123:
        return value / 65535.0
    return value


def _read_accessor(document, binary, accessor_index):
    accessor = document["accessors"][accessor_index]
    width = _ACCESSOR_WIDTHS[accessor["type"]]
    count = accessor["count"]
    component_type = accessor["componentType"]
    component_format = _COMPONENT_FORMATS[component_type]
    component_size = struct.calcsize("<" + component_format)
    element_size = component_size * width

    if "bufferView" not in accessor:
        return [[0.0] * width for _ in range(count)]

    view = document["bufferViews"][accessor["bufferView"]]
    offset = view.get("byteOffset", 0) + accessor.get("byteOffset", 0)
    stride = view.get("byteStride", element_size)
    unpack_format = "<" + component_format * width
    normalized = accessor.get("normalized", False)
    values = []

    for index in range(count):
        item = list(struct.unpack_from(
            unpack_format, binary, offset + index * stride
        ))
        if normalized:
            item = [
                _normalize_component(value, component_type)
                for value in item
            ]
        values.append(item)
    return values


# ============================================================================
# Track extraction and optimization
# ============================================================================

def _node_rest_value(document, node_index, path):
    node = document["nodes"][node_index]
    if path == "translation":
        return node.get("translation", [0.0, 0.0, 0.0])
    if path == "rotation":
        return node.get("rotation", [0.0, 0.0, 0.0, 1.0])
    if path == "scale":
        return node.get("scale", [1.0, 1.0, 1.0])
    return None


def _three_node_names(document):
    """Mirror GLTFLoader/PropertyBinding node-name sanitizing and uniqueness."""
    result = {}
    used = {}
    for index, node in enumerate(document.get("nodes", [])):
        original = node.get("name") or f"node_{index}"
        sanitized = re.sub(r"\s", "_", original)
        sanitized = re.sub(r"[\[\]\.:/]", "", sanitized) or f"node_{index}"
        duplicate_index = used.get(sanitized, 0)
        used[sanitized] = duplicate_index + 1
        result[index] = (
            sanitized if duplicate_index == 0
            else f"{sanitized}_{duplicate_index}"
        )
    return result


def _quat_normalize(quaternion):
    length = math.sqrt(sum(value * value for value in quaternion))
    if length <= 1e-12:
        return [0.0, 0.0, 0.0, 1.0]
    return [value / length for value in quaternion]


def _quat_slerp(first, second, factor):
    first = _quat_normalize(first)
    second = _quat_normalize(second)
    dot = sum(a * b for a, b in zip(first, second))
    if dot < 0.0:
        second = [-value for value in second]
        dot = -dot
    dot = min(1.0, max(-1.0, dot))
    if dot > 0.9995:
        return _quat_normalize([
            a + factor * (b - a) for a, b in zip(first, second)
        ])
    angle = math.acos(dot)
    sine = math.sin(angle)
    left = math.sin((1.0 - factor) * angle) / sine
    right = math.sin(factor * angle) / sine
    return [left * a + right * b for a, b in zip(first, second)]


def _close_values(first, second, epsilon):
    return len(first) == len(second) and all(
        abs(a - b) <= epsilon for a, b in zip(first, second)
    )


def _interpolated_value(first, second, factor, property_name):
    if property_name == "quaternion":
        return _quat_slerp(first, second, factor)
    return [a + factor * (b - a) for a, b in zip(first, second)]


def _optimize_track(times, values, property_name, rest_value):
    if not times or len(times) != len(values):
        return None
    epsilon = 10.0 ** (-DECIMAL_PRECISION)

    if property_name == "quaternion":
        normalized = []
        for value in values:
            value = _quat_normalize(value)
            if normalized and sum(
                a * b for a, b in zip(normalized[-1], value)
            ) < 0.0:
                value = [-component for component in value]
            normalized.append(value)
        values = normalized

    if rest_value is not None and all(
        _close_values(value, rest_value, epsilon) for value in values
    ):
        return None

    if len(times) > 2:
        kept_indices = [0]
        for index in range(1, len(times) - 1):
            previous = kept_indices[-1]
            following = index + 1
            span = times[following] - times[previous]
            if abs(span) <= 1e-12:
                kept_indices.append(index)
                continue
            factor = (times[index] - times[previous]) / span
            predicted = _interpolated_value(
                values[previous], values[following], factor, property_name
            )
            if not _close_values(values[index], predicted, epsilon):
                kept_indices.append(index)
        kept_indices.append(len(times) - 1)
        times = [times[index] for index in kept_indices]
        values = [values[index] for index in kept_indices]

    rounded_times = [_round_float(value) for value in times]
    rounded_values = [
        [_round_float(component) for component in value]
        for value in values
    ]
    return rounded_times, rounded_values


def _round_float(value):
    rounded = round(float(value), DECIMAL_PRECISION)
    return 0.0 if abs(rounded) < 10.0 ** (-DECIMAL_PRECISION) else rounded


def _take_cubic_spline_values(rows):
    return [rows[index] for index in range(1, len(rows), 3)]


def _extract_standard_track(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    path = channel["target"]["path"]
    target_name = node_names[node_index]
    times = [row[0] for row in _read_accessor(
        document, binary, sampler["input"]
    )]
    values = _read_accessor(document, binary, sampler["output"])
    interpolation = sampler.get("interpolation", "LINEAR")
    if interpolation == "CUBICSPLINE":
        values = _take_cubic_spline_values(values)

    property_map = {
        "translation": "position",
        "rotation": "quaternion",
        "scale": "scale",
    }
    property_name = property_map[path]
    optimized = _optimize_track(
        times, values, property_name,
        _node_rest_value(document, node_index, path),
    )
    if not optimized:
        return None
    times, values = optimized
    return {
        "target": target_name,
        "property": property_name,
        "times": times,
        "values": [component for value in values for component in value],
        **({"interpolation": "discrete"}
           if interpolation == "STEP" else {}),
    }


def _extract_weight_tracks(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    node = document["nodes"][node_index]
    target_name = node_names[node_index]
    mesh = document["meshes"][node["mesh"]]
    target_names = mesh.get("extras", {}).get("targetNames", [])
    times = [row[0] for row in _read_accessor(
        document, binary, sampler["input"]
    )]
    rows = _read_accessor(document, binary, sampler["output"])
    flat = [component for row in rows for component in row]
    interpolation = sampler.get("interpolation", "LINEAR")

    divisor = len(times) * (3 if interpolation == "CUBICSPLINE" else 1)
    target_count = len(flat) // divisor if divisor else 0
    if target_count == 0:
        return []

    if interpolation == "CUBICSPLINE":
        sampled = []
        block = target_count * 3
        for index in range(len(times)):
            start = index * block + target_count
            sampled.append(flat[start:start + target_count])
    else:
        sampled = [
            flat[index * target_count:(index + 1) * target_count]
            for index in range(len(times))
        ]

    rest_weights = node.get("weights", mesh.get(
        "weights", [0.0] * target_count
    ))
    tracks = []
    for target_index in range(target_count):
        values = [[sample[target_index]] for sample in sampled]
        rest = [rest_weights[target_index]
                if target_index < len(rest_weights) else 0.0]
        optimized = _optimize_track(
            times, values,
            f"morphTargetInfluences[{target_index}]",
            rest,
        )
        if not optimized:
            continue
        track_times, track_values = optimized
        track = {
            "target": target_name,
            "property": f"morphTargetInfluences[{target_index}]",
            "times": track_times,
            "values": [value[0] for value in track_values],
        }
        if target_index < len(target_names):
            track["morphTarget"] = target_names[target_index]
        if interpolation == "STEP":
            track["interpolation"] = "discrete"
        tracks.append(track)
    return tracks


def _extract_animation_data(document, binary, wanted_names, effective_fps):
    grouped = {}
    node_names = _three_node_names(document)
    for animation_index, animation in enumerate(
        document.get("animations", [])
    ):
        name = animation.get("name") or f"Animation_{animation_index + 1}"
        if name not in wanted_names:
            continue
        entry = grouped.setdefault(name, {"name": name, "tracks": []})
        for channel in animation.get("channels", []):
            sampler = animation["samplers"][channel["sampler"]]
            path = channel.get("target", {}).get("path")
            if path in {"translation", "rotation", "scale"}:
                track = _extract_standard_track(
                    document, binary, channel, sampler, node_names
                )
                if track:
                    entry["tracks"].append(track)
            elif path == "weights":
                entry["tracks"].extend(_extract_weight_tracks(
                    document, binary, channel, sampler, node_names
                ))

    result = []
    for name in sorted(grouped, key=str.casefold):
        entry = grouped[name]
        duration = max(
            (max(track["times"]) for track in entry["tracks"]
             if track["times"]),
            default=0.0,
        )
        entry["duration"] = _round_float(duration)
        entry["fps"] = _round_float(effective_fps)
        entry["tracks"].sort(
            key=lambda track: (track["target"], track["property"])
        )
        result.append(entry)
    return result


# ============================================================================
# TypeScript generation
# ============================================================================

def _safe_identifier(name):
    identifier = re.sub(r"\W+", "_", name, flags=re.UNICODE).strip("_")
    if not identifier:
        identifier = "Animation"
    if identifier[0].isdigit() or identifier in _TS_RESERVED:
        identifier = f"Animation_{identifier}"
    return identifier


def _safe_filename(name):
    filename = re.sub(r'[<>:"/\\|?*\x00-\x1F]+', "_", name).strip(" .")
    if not filename:
        filename = "Animation"
    if filename.upper() in _WINDOWS_RESERVED:
        filename = f"Animation_{filename}"
    return filename


def _unique_names(animations):
    used_identifiers = set()
    used_files = set()
    result = []
    for animation in animations:
        base_identifier = _safe_identifier(animation["name"])
        base_file = _safe_filename(animation["name"])
        identifier = base_identifier
        filename = base_file
        suffix = 2
        while (identifier.casefold() in used_identifiers or
               filename.casefold() in used_files):
            identifier = f"{base_identifier}_{suffix}"
            filename = f"{base_file}_{suffix}"
            suffix += 1
        used_identifiers.add(identifier.casefold())
        used_files.add(filename.casefold())
        result.append((animation, identifier, filename))
    return result


def _atomic_write(filepath, content):
    temporary = filepath + ".tmp"
    with open(temporary, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    os.replace(temporary, filepath)


def _remove_old_generated_animation_files(animation_dir):
    if not os.path.isdir(animation_dir):
        return
    for filename in os.listdir(animation_dir):
        if not filename.endswith(".ts"):
            continue
        filepath = os.path.join(animation_dir, filename)
        try:
            with open(filepath, "r", encoding="utf-8") as handle:
                first_line = handle.readline().rstrip("\r\n")
            if first_line == _GENERATED_MARKER:
                os.remove(filepath)
        except OSError:
            continue


def _animation_module(animation, identifier):
    compact = json.dumps(
        animation, ensure_ascii=False, separators=(",", ":"), allow_nan=False
    )
    return (
        f"{_GENERATED_MARKER}\n"
        'import type { AnimationData } from "../animationClipFactory";\n\n'
        f"export const {identifier} = {compact} as const "
        "satisfies AnimationData;\n"
        f"export default {identifier};\n"
    )


def _index_module(named_animations):
    imports = "\n".join(
        f'import {{ {identifier} }} from "./{filename}";'
        for _animation, identifier, filename in named_animations
    )
    exports = ", ".join(
        identifier for _animation, identifier, _filename in named_animations
    )
    return (
        f"{_GENERATED_MARKER}\n"
        f"{imports}\n\n"
        f"export {{ {exports} }};\n"
        f"export const animations = [{exports}] as const;\n"
    )


def _factory_module():
    return f"""{_GENERATED_MARKER}
import * as THREE from "three";

export type AnimationProperty =
  | "position"
  | "quaternion"
  | "scale"
  | `morphTargetInfluences[${{number}}]`;

export interface AnimationTrackData {{
  readonly target: string;
  readonly property: AnimationProperty;
  readonly times: readonly number[];
  readonly values: readonly number[];
  readonly interpolation?: "linear" | "discrete";
  readonly morphTarget?: string;
}}

export interface AnimationData {{
  readonly name: string;
  readonly duration: number;
  readonly fps: number;
  readonly tracks: readonly AnimationTrackData[];
}}

function createTrack(track: AnimationTrackData): THREE.KeyframeTrack {{
  const binding = `${{track.target}}.${{track.property}}`;
  const times = Array.from(track.times);
  const values = Array.from(track.values);
  let result: THREE.KeyframeTrack;

  if (track.property === "quaternion") {{
    result = new THREE.QuaternionKeyframeTrack(binding, times, values);
  }} else if (
    track.property === "position" ||
    track.property === "scale"
  ) {{
    result = new THREE.VectorKeyframeTrack(binding, times, values);
  }} else {{
    result = new THREE.NumberKeyframeTrack(binding, times, values);
  }}

  if (track.interpolation === "discrete") {{
    result.setInterpolation(THREE.InterpolateDiscrete);
  }}
  return result;
}}

export function createAnimationClip(
  animation: AnimationData,
): THREE.AnimationClip {{
  const tracks = animation.tracks.map(createTrack);
  return new THREE.AnimationClip(animation.name, animation.duration, tracks);
}}

export function createAnimationClips(
  animations: readonly AnimationData[],
): THREE.AnimationClip[] {{
  return animations.map(createAnimationClip);
}}
"""


# ============================================================================
# Binary animation encoding, validation, and reporting
# ============================================================================

_MAGIC = b"T3AN"
_FORMAT_VERSION = 1
_HEADER_SIZE = 32
_PROPERTY_CODES = {"position": 0, "quaternion": 1, "scale": 2, "morph": 3}
_INTERPOLATION_CODES = {"LINEAR": 0, "STEP": 1}
_ENCODING_FLOAT32 = 0
_ENCODING_QUAT_INT16 = 1
_ENCODING_VECTOR_UINT16 = 2
_ENCODING_SCALAR_UINT16 = 3
_TIME_UNIFORM = 0
_TIME_UINT16 = 1
_TIME_UINT32 = 2
_TIME_FLOAT32 = 3


def _progress(value, message):
    print(f"[Binary Animation Export] {value:3d}% {message}")
    if PROGRESS_CALLBACK:
        PROGRESS_CALLBACK(int(value), message)


def _human_size(byte_count):
    size = float(byte_count)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024.0 or unit == "GB":
            return f"{size:.1f} {unit}"
        size /= 1024.0


def _animated_ids(objects):
    result = list(objects)
    for obj in objects:
        if obj.type == "MESH" and obj.data.shape_keys:
            result.append(obj.data.shape_keys)
    return result


def _snapshot_scene_state(objects):
    active = bpy.context.view_layer.objects.active
    animation_state = []
    for data_block in _animated_ids(objects):
        animation_data = getattr(data_block, "animation_data", None)
        if not animation_data:
            continue
        nla_state = []
        for track in animation_data.nla_tracks:
            strips = [(strip, getattr(strip, "mute", None)) for strip in track.strips]
            nla_state.append((track, getattr(track, "mute", None), getattr(track, "is_solo", None), strips))
        animation_state.append((
            data_block, animation_data.action, getattr(animation_data, "use_nla", None),
            getattr(animation_data, "action_blend_type", None),
            getattr(animation_data, "action_extrapolation", None),
            getattr(animation_data, "action_influence", None), nla_state,
        ))
    scene = bpy.context.scene
    return {
        "active": active.name if active else None,
        "mode": active.mode if active else "OBJECT",
        "selected": [obj.name for obj in bpy.context.selected_objects],
        "hidden": {obj.name: (obj.hide_get(), obj.hide_viewport) for obj in objects},
        "frame": scene.frame_current,
        "subframe": scene.frame_subframe,
        "frame_start": scene.frame_start,
        "frame_end": scene.frame_end,
        "use_preview_range": scene.use_preview_range,
        "frame_preview_start": scene.frame_preview_start,
        "frame_preview_end": scene.frame_preview_end,
        "animation": animation_state,
    }


def _set_if_available(owner, attribute, value):
    if value is not None and hasattr(owner, attribute):
        try:
            setattr(owner, attribute, value)
        except (AttributeError, RuntimeError, TypeError):
            pass


def _ensure_object_mode():
    active = bpy.context.view_layer.objects.active
    if active and active.mode != "OBJECT":
        try:
            bpy.ops.object.mode_set(mode="OBJECT")
        except RuntimeError:
            pass


def _restore_scene_state(state):
    _ensure_object_mode()
    scene = bpy.context.scene
    for record in state["animation"]:
        data_block, action, use_nla, blend, extrapolation, influence, nla_state = record
        animation_data = getattr(data_block, "animation_data", None)
        if not animation_data:
            continue
        try:
            animation_data.action = action
        except (AttributeError, RuntimeError):
            pass
        _set_if_available(animation_data, "use_nla", use_nla)
        _set_if_available(animation_data, "action_blend_type", blend)
        _set_if_available(animation_data, "action_extrapolation", extrapolation)
        _set_if_available(animation_data, "action_influence", influence)
        for track, mute, is_solo, strips in nla_state:
            _set_if_available(track, "mute", mute)
            _set_if_available(track, "is_solo", is_solo)
            for strip, strip_mute in strips:
                _set_if_available(strip, "mute", strip_mute)
    scene.frame_start = state["frame_start"]
    scene.frame_end = state["frame_end"]
    scene.use_preview_range = state["use_preview_range"]
    scene.frame_preview_start = state["frame_preview_start"]
    scene.frame_preview_end = state["frame_preview_end"]
    scene.frame_set(state["frame"], subframe=state["subframe"])
    for name, (hidden, hide_viewport) in state["hidden"].items():
        obj = bpy.data.objects.get(name)
        if obj:
            obj.hide_set(hidden)
            obj.hide_viewport = hide_viewport
    try:
        bpy.ops.object.select_all(action="DESELECT")
    except RuntimeError:
        pass
    for name in state["selected"]:
        obj = bpy.data.objects.get(name)
        if obj:
            try:
                obj.select_set(True)
            except RuntimeError:
                pass
    active = bpy.data.objects.get(state["active"]) if state["active"] else None
    if active:
        bpy.context.view_layer.objects.active = active
        if state["mode"] != "OBJECT":
            try:
                bpy.ops.object.mode_set(mode=state["mode"])
            except RuntimeError:
                print(f"[Binary Animation Export] Could not restore mode {state['mode']}.")


def _extract_raw_standard_track(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    path = channel["target"]["path"]
    times = [row[0] for row in _read_accessor(document, binary, sampler["input"])]
    values = _read_accessor(document, binary, sampler["output"])
    interpolation = sampler.get("interpolation", "LINEAR")
    if interpolation == "CUBICSPLINE":
        values = _take_cubic_spline_values(values)
        interpolation = "LINEAR"
    property_name = {"translation": "position", "rotation": "quaternion", "scale": "scale"}[path]
    return {
        "target": node_names[node_index], "property": property_name, "morph_index": 0xFFFF,
        "interpolation": interpolation, "times": [float(value) for value in times],
        "values": [[float(component) for component in row] for row in values],
        "rest": [float(value) for value in _node_rest_value(document, node_index, path)],
    }


def _extract_raw_weight_tracks(document, binary, channel, sampler, node_names):
    node_index = channel["target"]["node"]
    node = document["nodes"][node_index]
    mesh = document["meshes"][node["mesh"]]
    times = [row[0] for row in _read_accessor(document, binary, sampler["input"])]
    rows = _read_accessor(document, binary, sampler["output"])
    flat = [component for row in rows for component in row]
    interpolation = sampler.get("interpolation", "LINEAR")
    divisor = len(times) * (3 if interpolation == "CUBICSPLINE" else 1)
    target_count = len(flat) // divisor if divisor else 0
    if target_count == 0:
        return []
    if interpolation == "CUBICSPLINE":
        sampled = []
        block = target_count * 3
        for index in range(len(times)):
            start = index * block + target_count
            sampled.append(flat[start:start + target_count])
        interpolation = "LINEAR"
    else:
        sampled = [flat[index * target_count:(index + 1) * target_count] for index in range(len(times))]
    rest_weights = node.get("weights", mesh.get("weights", [0.0] * target_count))
    return [{
        "target": node_names[node_index], "property": "morph", "morph_index": target_index,
        "interpolation": interpolation, "times": [float(value) for value in times],
        "values": [[float(row[target_index])] for row in sampled],
        "rest": [float(rest_weights[target_index] if target_index < len(rest_weights) else 0.0)],
    } for target_index in range(target_count)]


def _extract_raw_animation_data(document, binary, wanted_names, effective_fps):
    grouped = {}
    node_names = _three_node_names(document)
    for animation_index, animation in enumerate(document.get("animations", [])):
        name = animation.get("name") or f"Animation_{animation_index + 1}"
        if name not in wanted_names:
            continue
        entry = grouped.setdefault(name, {"name": name, "tracks": [], "duration": 0.0})
        for channel in animation.get("channels", []):
            sampler = animation["samplers"][channel["sampler"]]
            path = channel.get("target", {}).get("path")
            if path in {"translation", "rotation", "scale"}:
                entry["tracks"].append(_extract_raw_standard_track(document, binary, channel, sampler, node_names))
            elif path == "weights":
                entry["tracks"].extend(_extract_raw_weight_tracks(document, binary, channel, sampler, node_names))
        entry["duration"] = max((max(track["times"]) for track in entry["tracks"] if track["times"]), default=0.0)
        entry["fps"] = float(effective_fps)
    return [grouped[name] for name in sorted(grouped, key=str.casefold)]


def _exact_sample_times(duration, fps):
    """Return a requested-FPS time grid while always preserving the endpoint."""
    duration = max(0.0, float(duration))
    fps = float(fps)
    if duration <= 1e-12:
        return [0.0]

    whole_steps = int(math.floor(duration * fps + 1e-9))
    times = [index / fps for index in range(whole_steps + 1)]
    endpoint_epsilon = max(1e-7, 1.0 / fps * 1e-6)
    if abs(times[-1] - duration) <= endpoint_epsilon:
        times[-1] = duration
    elif times[-1] < duration:
        times.append(duration)
    return times


def _resample_raw_animations(animations, fps):
    """Resample evaluated glTF-space tracks at the exact requested rate."""
    requested_fps = float(fps)
    result = []
    for animation in animations:
        duration = float(animation.get("duration", 0.0))
        sample_times = _exact_sample_times(duration, requested_fps)
        tracks = []
        for track in animation["tracks"]:
            source_times = track["times"]
            source_values = track["values"]
            if not source_times or len(source_times) != len(source_values):
                continue
            sampled_values = [
                list(_sample_values(
                    source_times,
                    source_values,
                    target_time,
                    track["property"],
                    track.get("interpolation", "LINEAR"),
                ))
                for target_time in sample_times
            ]
            tracks.append({
                **track,
                "times": list(sample_times),
                "values": sampled_values,
            })
        result.append({
            **animation,
            "duration": duration,
            "fps": requested_fps,
            "tracks": tracks,
        })
    return result


def _track_tolerance(property_name):
    if property_name == "position":
        return POSITION_TOLERANCE
    if property_name == "quaternion":
        return math.radians(ROTATION_TOLERANCE_DEGREES)
    if property_name == "scale":
        return SCALE_TOLERANCE
    return MORPH_TOLERANCE


def _property_error(property_name, first, second):
    if property_name == "quaternion":
        a = _quat_normalize(first)
        b = _quat_normalize(second)
        dot = min(1.0, max(-1.0, abs(sum(x * y for x, y in zip(a, b)))))
        return 2.0 * math.acos(dot)
    if property_name == "position":
        return math.sqrt(sum((a - b) ** 2 for a, b in zip(first, second)))
    return max((abs(a - b) for a, b in zip(first, second)), default=0.0)


def _sample_values(times, values, target_time, property_name, interpolation="LINEAR"):
    if len(times) == 1 or target_time <= times[0]:
        return values[0]
    if target_time >= times[-1]:
        return values[-1]
    low, high = 0, len(times) - 1
    while low + 1 < high:
        middle = (low + high) // 2
        if times[middle] <= target_time:
            low = middle
        else:
            high = middle
    if interpolation == "STEP":
        return values[low]
    span = times[high] - times[low]
    factor = 0.0 if abs(span) <= 1e-12 else (target_time - times[low]) / span
    return _interpolated_value(values[low], values[high], factor, property_name)


def _reduce_linear_indices(times, values, property_name, tolerance):
    keep = {0, len(times) - 1}
    stack = [(0, len(times) - 1)]
    while stack:
        start, end = stack.pop()
        if end <= start + 1:
            continue
        span = times[end] - times[start]
        worst_error, worst_index = -1.0, None
        for index in range(start + 1, end):
            factor = 0.0 if abs(span) <= 1e-12 else (times[index] - times[start]) / span
            predicted = _interpolated_value(values[start], values[end], factor, property_name)
            error = _property_error(property_name, values[index], predicted)
            if error > worst_error:
                worst_error, worst_index = error, index
        if worst_index is not None and worst_error > tolerance:
            keep.add(worst_index)
            stack.append((start, worst_index))
            stack.append((worst_index, end))
    return sorted(keep)


def _optimize_binary_track(raw_track):
    times = raw_track["times"]
    original_values = raw_track["values"]
    if not times or len(times) != len(original_values):
        return None
    property_name = raw_track["property"]
    tolerance = _track_tolerance(property_name)
    values = []
    for value in original_values:
        rounded = [round(float(component), DECIMAL_PRECISION) for component in value]
        if property_name == "quaternion":
            rounded = _quat_normalize(rounded)
            if values and sum(a * b for a, b in zip(values[-1], rounded)) < 0.0:
                rounded = [-component for component in rounded]
        values.append(rounded)
    is_constant = all(_property_error(property_name, values[0], value) <= tolerance for value in values[1:])
    if is_constant:
        matches_rest = raw_track["rest"] is not None and all(
            _property_error(property_name, value, raw_track["rest"]) <= tolerance for value in values
        )
        if REMOVE_STATIC_TRACKS and matches_rest:
            return None
        indices = [0]
    elif raw_track["interpolation"] == "STEP":
        indices = [0]
        for index in range(1, len(times)):
            if _property_error(property_name, values[index - 1], values[index]) > tolerance:
                indices.append(index)
        if indices[-1] != len(times) - 1:
            indices.append(len(times) - 1)
    elif ENABLE_KEYFRAME_REDUCTION and len(times) > 2:
        indices = _reduce_linear_indices(times, values, property_name, tolerance * 0.9)
    else:
        indices = list(range(len(times)))
    return {
        **{key: raw_track[key] for key in ("target", "property", "morph_index", "interpolation")},
        "times": [times[index] for index in indices],
        "values": [values[index] for index in indices],
        "original_times": times, "original_values": original_values,
    }


def _quantization_allowed(property_name):
    return ENABLE_QUANTIZATION and (
        (property_name == "quaternion" and QUANTIZE_QUATERNIONS) or
        (property_name == "position" and QUANTIZE_POSITIONS) or
        (property_name == "scale" and QUANTIZE_SCALES) or
        (property_name == "morph" and QUANTIZE_MORPHS)
    )


def _choose_value_encoding(track):
    values = track["values"]
    property_name = track["property"]
    tolerance = _track_tolerance(property_name)
    if not _quantization_allowed(property_name):
        return _ENCODING_FLOAT32, None, values
    if property_name == "quaternion":
        encoded, decoded = [], []
        for value in values:
            row = [max(-32767, min(32767, int(round(component * 32767.0)))) for component in value]
            encoded.append(row)
            decoded.append(_quat_normalize([component / 32767.0 for component in row]))
        error = max((_property_error(property_name, source, rebuilt) for source, rebuilt in zip(values, decoded)), default=0.0)
        if error <= tolerance:
            return _ENCODING_QUAT_INT16, encoded, decoded
        return _ENCODING_FLOAT32, None, values
    width = len(values[0])
    minimum = [min(row[index] for row in values) for index in range(width)]
    maximum = [max(row[index] for row in values) for index in range(width)]
    encoded, decoded = [], []
    for value in values:
        encoded_row, decoded_row = [], []
        for index, component in enumerate(value):
            span = maximum[index] - minimum[index]
            quantized = 0 if abs(span) <= 1e-20 else int(round((component - minimum[index]) * 65535.0 / span))
            quantized = max(0, min(65535, quantized))
            encoded_row.append(quantized)
            decoded_row.append(minimum[index] if abs(span) <= 1e-20 else minimum[index] + (quantized / 65535.0) * span)
        encoded.append(encoded_row)
        decoded.append(decoded_row)
    error = max((_property_error(property_name, source, rebuilt) for source, rebuilt in zip(values, decoded)), default=0.0)
    if error <= tolerance:
        encoding = _ENCODING_SCALAR_UINT16 if width == 1 else _ENCODING_VECTOR_UINT16
        return encoding, {"minimum": minimum, "maximum": maximum, "values": encoded}, decoded
    return _ENCODING_FLOAT32, None, values


def _choose_time_encoding(times, fps):
    sample_indices = [int(round(value * fps)) for value in times]
    on_grid = all(abs(value - index / fps) <= 1e-5 for value, index in zip(times, sample_indices))
    if on_grid:
        if len(sample_indices) <= 1:
            return _TIME_UNIFORM, (sample_indices[0] if sample_indices else 0, 0)
        step = sample_indices[1] - sample_indices[0]
        if all(sample_indices[index] - sample_indices[index - 1] == step for index in range(2, len(sample_indices))):
            return _TIME_UNIFORM, (sample_indices[0], step)
        if min(sample_indices) >= 0 and max(sample_indices) <= 0xFFFF:
            return _TIME_UINT16, sample_indices
        if min(sample_indices) >= 0:
            return _TIME_UINT32, sample_indices
    return _TIME_FLOAT32, times


def _validate_optimized_track(track, decoded_values):
    maximum = 0.0
    for time_value, source in zip(track["original_times"], track["original_values"]):
        rebuilt = _sample_values(track["times"], decoded_values, time_value, track["property"], track["interpolation"])
        maximum = max(maximum, _property_error(track["property"], source, rebuilt))
    return maximum


def _align(data, alignment=4):
    padding = (-len(data)) % alignment
    if padding:
        data.extend(b"\0" * padding)


def _append_values(data, fmt, rows):
    packer = struct.Struct("<" + fmt)
    for row in rows:
        for value in row:
            data.extend(packer.pack(value))


def _write_binary_animation(filepath, animation, target_ids, mapping_hash):
    data = bytearray(b"\0" * _HEADER_SIZE)
    total_keys = 0
    contains_quantization = False
    validation = dict(animation.get("removed_validation", {"position": 0.0, "quaternion": 0.0, "scale": 0.0, "morph": 0.0}))
    for track in animation["tracks"]:
        target_id = target_ids[track["target"]]
        encoding, encoded, decoded_values = _choose_value_encoding(track)
        time_mode, time_payload = _choose_time_encoding(track["times"], animation["fps"])
        validation[track["property"]] = max(validation[track["property"]], _validate_optimized_track(track, decoded_values))
        key_count = len(track["times"])
        component_count = len(track["values"][0])
        total_keys += key_count
        contains_quantization = contains_quantization or encoding != _ENCODING_FLOAT32
        data.extend(struct.pack("<HBBBBBBHHI", target_id, _PROPERTY_CODES[track["property"]],
            _INTERPOLATION_CODES.get(track["interpolation"], 0), encoding, time_mode,
            component_count, 0, track["morph_index"], 0, key_count))
        if time_mode == _TIME_UNIFORM:
            data.extend(struct.pack("<II", time_payload[0], time_payload[1]))
        elif time_mode == _TIME_UINT16:
            data.extend(struct.pack("<" + "H" * key_count, *time_payload))
        elif time_mode == _TIME_UINT32:
            data.extend(struct.pack("<" + "I" * key_count, *time_payload))
        else:
            data.extend(struct.pack("<" + "f" * key_count, *time_payload))
        _align(data)
        if encoding == _ENCODING_FLOAT32:
            _append_values(data, "f", track["values"])
        elif encoding == _ENCODING_QUAT_INT16:
            _append_values(data, "h", encoded)
        else:
            _append_values(data, "f", [encoded["minimum"], encoded["maximum"]])
            _append_values(data, "H", encoded["values"])
        _align(data)
    flags = 1 if contains_quantization else 0
    struct.pack_into("<4sHHffHHIII", data, 0, _MAGIC, _FORMAT_VERSION, _HEADER_SIZE,
        float(animation["duration"]), float(animation["fps"]), len(animation["tracks"]),
        flags, total_keys, mapping_hash, len(data))
    temporary = filepath + ".tmp"
    with open(temporary, "wb") as handle:
        handle.write(data)
    os.replace(temporary, filepath)
    return {"tracks": len(animation["tracks"]), "keyframes": total_keys, "size": len(data), "contentHash": f"{_fnv1a32(data):08x}", "validation": validation}


def _fnv1a32(data):
    value = 0x811C9DC5
    for byte in data:
        value ^= byte
        value = (value * 0x01000193) & 0xFFFFFFFF
    return value


def _build_target_mapping(base_document, raw_animations):
    node_names = _three_node_names(base_document)
    joint_indices = []
    for skin in base_document.get("skins", []):
        for node_index in skin.get("joints", []):
            if node_index not in joint_indices:
                joint_indices.append(node_index)
    bone_names = [node_names[index] for index in joint_indices]
    targets, used = [], set()
    for name in bone_names:
        if name not in used:
            targets.append({"name": name, "kind": "bone"})
            used.add(name)
    animated_names = sorted({track["target"] for animation in raw_animations for track in animation["tracks"]}, key=str.casefold)
    for name in animated_names:
        if name not in used:
            targets.append({"name": name, "kind": "object"})
            used.add(name)
    if len(targets) > 0xFFFF:
        raise RuntimeError("Binary format supports at most 65,535 animation targets.")
    target_ids = {entry["name"]: index for index, entry in enumerate(targets)}
    mapping_bytes = bytearray()
    for entry in targets:
        mapping_bytes.extend(entry["kind"].encode("utf-8"))
        mapping_bytes.append(0)
        mapping_bytes.extend(entry["name"].encode("utf-8"))
        mapping_bytes.append(0)
    return bone_names, targets, target_ids, _fnv1a32(mapping_bytes)


def _remove_previous_binary_files(output_dir, animation_dir):
    manifest_path = os.path.join(output_dir, MANIFEST_FILENAME)
    if not os.path.isfile(manifest_path):
        return
    try:
        with open(manifest_path, "r", encoding="utf-8") as handle:
            old_manifest = json.load(handle)
        animation_root = os.path.abspath(animation_dir)
        for metadata in old_manifest.get("animations", {}).values():
            candidate = os.path.abspath(os.path.join(output_dir, metadata.get("file", "")))
            if (candidate.lower().endswith(".anim") and
                    os.path.commonpath([candidate, animation_root]) == animation_root and
                    os.path.isfile(candidate)):
                os.remove(candidate)
    except (OSError, ValueError, TypeError, json.JSONDecodeError):
        print("[Binary Animation Export] Existing manifest cleanup skipped.")


def _safe_animation_filenames(animations):
    used, result = set(), []
    for animation in animations:
        base = _safe_filename(animation["name"])
        candidate, suffix = base, 2
        while candidate.casefold() in used:
            candidate = f"{base}_{suffix}"
            suffix += 1
        used.add(candidate.casefold())
        result.append((animation, candidate + ".anim"))
    return result


def export_character_and_animations():
    if not GLB_FILENAME.lower().endswith(".glb") or os.path.basename(GLB_FILENAME) != GLB_FILENAME:
        raise ValueError("GLB_FILENAME must be a filename ending in .glb.")
    if OUTPUT_DIRECTORY.startswith("//") and not bpy.data.filepath:
        raise RuntimeError("Save the .blend file first or configure an absolute OUTPUT_DIRECTORY.")
    if not 3 <= DECIMAL_PRECISION <= 9:
        raise ValueError("DECIMAL_PRECISION must be between 3 and 9.")
    if SAMPLING_FPS <= 0:
        raise ValueError("SAMPLING_FPS must be greater than zero.")
    if any(value < 0 for value in (POSITION_TOLERANCE, ROTATION_TOLERANCE_DEGREES, SCALE_TOLERANCE, MORPH_TOLERANCE)):
        raise ValueError("Animation tolerances cannot be negative.")

    output_dir = bpy.path.abspath(OUTPUT_DIRECTORY)
    animation_dir = os.path.join(output_dir, "animations")
    glb_path = os.path.join(output_dir, GLB_FILENAME)
    staging_path = os.path.join(output_dir, _STAGING_FILENAME)
    manifest_path = os.path.join(output_dir, MANIFEST_FILENAME)
    armature, meshes = _find_primary_armature()
    character_objects = _collect_character_objects(armature, meshes)
    actions = _find_character_actions(armature, meshes)
    wanted_names = {action.name for action in actions}
    scene_fps = bpy.context.scene.render.fps / bpy.context.scene.render.fps_base
    staging_frame_step = 1
    effective_fps = float(SAMPLING_FPS)
    os.makedirs(animation_dir, exist_ok=True)
    state = _snapshot_scene_state(character_objects)
    quarantine, quarantine_records = None, []
    generated_files = []
    _ensure_object_mode()

    try:
        _progress(2, f"Detected armature {armature.name} and {len(meshes)} skinned meshes")
        _export_glb(glb_path, character_objects, animations=False)
        base_document, _base_binary = _read_glb(glb_path)
        if base_document.get("animations"):
            raise RuntimeError("character.glb unexpectedly contains animations.")
        if not base_document.get("skins"):
            raise RuntimeError("character.glb contains no skin. Check Armature modifiers and vertex groups.")
        generated_files.append(glb_path)
        _progress(18, "Exported animation-free character GLB")

        raw_animations = []
        if actions:
            quarantine, quarantine_records = _quarantine_unsafe_fcurves()
            if quarantine_records:
                print(f"[Binary Animation Export] Temporarily skipped {len(quarantine_records)} unsupported F-curve(s); evaluated transforms remain sampled.")
            _progress(22, f"Sampling {len(actions)} evaluated Actions through Blender glTF")
            _export_glb(staging_path, character_objects, animations=True, frame_step=staging_frame_step)
            animation_document, animation_binary = _read_glb(staging_path)
            raw_animations = _extract_raw_animation_data(animation_document, animation_binary, wanted_names, scene_fps)
            raw_animations = _resample_raw_animations(raw_animations, effective_fps)
        exported_names = {animation["name"] for animation in raw_animations}
        missing = sorted(wanted_names - exported_names, key=str.casefold)
        if missing:
            raise RuntimeError("Blender did not emit these character Actions: " + ", ".join(missing))
        _progress(62, "Extracted evaluated glTF-space tracks")

        bone_names, targets, target_ids, mapping_hash = _build_target_mapping(base_document, raw_animations)
        optimized_animations = []
        for raw_animation in raw_animations:
            optimized_tracks = []
            removed_validation = {"position": 0.0, "quaternion": 0.0, "scale": 0.0, "morph": 0.0}
            for raw_track in raw_animation["tracks"]:
                optimized = _optimize_binary_track(raw_track)
                if optimized:
                    optimized_tracks.append(optimized)
                elif raw_track["rest"] is not None:
                    removed_validation[raw_track["property"]] = max(
                        removed_validation[raw_track["property"]],
                        max((_property_error(raw_track["property"], value, raw_track["rest"])
                             for value in raw_track["values"]), default=0.0),
                    )
            optimized_animations.append({
                "name": raw_animation["name"], "duration": raw_animation["duration"],
                "fps": raw_animation["fps"], "tracks": optimized_tracks,
                "original_tracks": len(raw_animation["tracks"]),
                "removed_validation": removed_validation,
                "original_keys": sum(len(track["times"]) for track in raw_animation["tracks"]),
            })

        _remove_previous_binary_files(output_dir, animation_dir)
        manifest_animations, reports = {}, []
        named = _safe_animation_filenames(optimized_animations)
        for index, (animation, filename) in enumerate(named):
            filepath = os.path.join(animation_dir, filename)
            encoded = _write_binary_animation(filepath, animation, target_ids, mapping_hash)
            generated_files.append(filepath)
            original_keys, optimized_keys = animation["original_keys"], encoded["keyframes"]
            reduction = 0.0 if original_keys == 0 else (1.0 - optimized_keys / original_keys) * 100.0
            errors = encoded["validation"]
            metadata = {
                "file": "animations/" + filename,
                "duration": round(animation["duration"], DECIMAL_PRECISION),
                "fps": round(animation["fps"], DECIMAL_PRECISION),
                "tracks": encoded["tracks"], "keyframes": optimized_keys, "size": encoded["size"],
                "contentHash": encoded["contentHash"],
                "validation": {
                    "originalSampledKeyframes": original_keys, "optimizedKeyframes": optimized_keys,
                    "reductionPercent": round(reduction, 2),
                    "maxPositionError": errors["position"],
                    "maxRotationErrorDegrees": math.degrees(errors["quaternion"]),
                    "maxScaleError": errors["scale"], "maxMorphError": errors["morph"],
                },
            }
            manifest_animations[animation["name"]] = metadata
            reports.append((animation["name"], metadata))
            _progress(65 + int(28 * (index + 1) / max(1, len(named))), f"Encoded {animation['name']}")

        manifest = {
            "version": _FORMAT_VERSION, "format": "T3AN", "character": GLB_FILENAME,
            "source": os.path.basename(bpy.data.filepath) if bpy.data.filepath else None,
            "mappingHash": mapping_hash, "skeleton": bone_names,
            "objects": [entry["name"] for entry in targets if entry["kind"] == "object"],
            "properties": {"position": 0, "quaternion": 1, "scale": 2, "morphTarget": 3},
            "animations": manifest_animations,
        }
        _atomic_write(manifest_path, json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
        generated_files.append(manifest_path)
        _progress(98, "Validated binary files and wrote manifest")

        print("\n" + "=" * 92)
        print("THREE.JS BINARY CHARACTER EXPORT COMPLETE")
        print("=" * 92)
        print(f"Character GLB: {glb_path}")
        print(f"Manifest: {manifest_path}")
        print(f"Armature: {armature.name} | Skeleton: {len(bone_names)} | Targets: {len(targets)}")
        print(f"Effective sampling FPS: {effective_fps:g} (scene {scene_fps:g}, exact time-grid resampling)")
        for name, metadata in reports:
            validation = metadata["validation"]
            print(f"  {name}: {metadata['tracks']} tracks | {validation['originalSampledKeyframes']} -> "
                  f"{metadata['keyframes']} keys ({validation['reductionPercent']:.2f}% reduction) | "
                  f"{_human_size(metadata['size'])} | max pos {validation['maxPositionError']:.7g}, "
                  f"rot {validation['maxRotationErrorDegrees']:.7g} deg, scale {validation['maxScaleError']:.7g}")
        print("Generated files:")
        for filepath in generated_files:
            print(f"  {filepath} — {_human_size(os.path.getsize(filepath))}")
        print("=" * 92)
        _progress(100, "Complete")
        return {
            "character_glb": glb_path, "manifest": manifest_path, "animations": manifest_animations,
            "tracks": sum(item["tracks"] for item in manifest_animations.values()),
            "keyframes": sum(item["keyframes"] for item in manifest_animations.values()),
            "files": generated_files,
        }
    finally:
        if quarantine:
            try:
                _restore_quarantined_fcurves(quarantine, quarantine_records)
            except Exception:
                print("[Binary Animation Export] ERROR restoring quarantined F-curves; copies remain in __TJS_EXPORT_QUARANTINE__.")
                traceback.print_exc()
        if os.path.isfile(staging_path):
            try:
                os.remove(staging_path)
            except OSError:
                pass
        _restore_scene_state(state)


if __name__ == "__main__":
    try:
        export_character_and_animations()
    except Exception:
        print("[Binary Animation Export] FAILED")
        traceback.print_exc()
        raise
