"""
Target optimization presets for Web3D Asset Compiler.
"""

PRESETS = {
    'R3F_OPTIMIZED': {
        'label': 'React Three Fiber - Balanced',
        'description': 'Balanced for modern web applications: 2K Atlas, 30 FPS, Int16 quantization, Draco level 6, WebP.',
        'ahb': {
            'bake_target': 'IMAGE_TEXTURES',
            'multires_bake': False,
            'resolution': '2048',
            'image_mode': 'ATLAS',
            'image_format': 'PNG',
            'use_hdr_float': False,
            'auto_create_uv': True,
            'uv_mode': 'SMART',
            'pack_enabled': True,
            'pack_world_scale': True,
            'pack_margin_px': 16,
            'samples': 128,
            'save_mode': 'EXTERNAL',
            'auto_save': True,
        },
        'tjs': {
            'portfolio_one_click': False,
            'export_format': 'GLB',
            'export_skins': True,
            'include_materials': True,
            'export_materials_mode': 'EXPORT',
            'include_textures': True,
            'image_format': 'WEBP',
            'texture_quality': 85,
            'compression': 'DRACO',
            'draco_level': 6,
            'animation_mode': 'ACTIONS',
            'export_all_actions': True,
            'sampling_fps': 30,
            'keyframe_reduction': True,
            'remove_static_tracks': True,
            'enable_animation_quantization': True,
            'quantize_quaternions': True,
            'quantize_positions': True,
            'quantize_scales': True,
            'quantize_morphs': True,
        }
    },
    'THREEJS_PORTFOLIO': {
        'label': 'Three.js - High Quality',
        'description': 'Maximum visual fidelity for portfolio showcases: 4K Atlas, uncompressed GLB, high precision float keyframes.',
        'ahb': {
            'bake_target': 'IMAGE_TEXTURES',
            'multires_bake': False,
            'resolution': '4096',
            'image_mode': 'ATLAS',
            'image_format': 'PNG',
            'use_hdr_float': False,
            'auto_create_uv': True,
            'uv_mode': 'SMART',
            'pack_enabled': True,
            'pack_world_scale': True,
            'pack_margin_px': 16,
            'samples': 256,
            'save_mode': 'EXTERNAL',
            'auto_save': True,
        },
        'tjs': {
            'portfolio_one_click': False,
            'export_format': 'GLB',
            'export_skins': True,
            'include_materials': True,
            'export_materials_mode': 'EXPORT',
            'include_textures': True,
            'image_format': 'AUTO',
            'texture_quality': 95,
            'compression': 'NONE',
            'animation_mode': 'ACTIONS',
            'export_all_actions': True,
            'sampling_fps': 30,
            'keyframe_reduction': False,
            'remove_static_tracks': False,
            'enable_animation_quantization': False,
        }
    },
    'MOBILE_WEB_LIGHT': {
        'label': 'Mobile Web - Lightweight',
        'description': 'Ultra-compact assets for mobile browsers: 1K Auto Tiles, 15 FPS keyframe reduction, Draco level 8, WebP 75%.',
        'ahb': {
            'bake_target': 'IMAGE_TEXTURES',
            'multires_bake': False,
            'resolution': '1024',
            'image_mode': 'AUTO_TILES',
            'tile_count': 4,
            'image_format': 'JPEG',
            'use_hdr_float': False,
            'auto_create_uv': True,
            'uv_mode': 'SMART',
            'pack_enabled': True,
            'pack_margin_px': 8,
            'samples': 64,
            'save_mode': 'EXTERNAL',
            'auto_save': True,
        },
        'tjs': {
            'portfolio_one_click': False,
            'export_format': 'GLB',
            'export_skins': True,
            'include_materials': True,
            'export_materials_mode': 'EXPORT',
            'include_textures': True,
            'image_format': 'WEBP',
            'texture_quality': 75,
            'compression': 'DRACO',
            'draco_level': 8,
            'animation_mode': 'ACTIONS',
            'export_all_actions': True,
            'sampling_fps': 15,
            'keyframe_reduction': True,
            'remove_static_tracks': True,
            'enable_animation_quantization': True,
            'quantize_quaternions': True,
            'quantize_positions': True,
            'quantize_scales': True,
            'quantize_morphs': True,
        }
    },
    'ARCHVIZ_LIGHTMAP': {
        'label': 'ArchViz - Lightmap Quality',
        'description': 'High-resolution lightmaps for architectural scenes: 4K EXR, Auto Seam Unwrap, World-Space Proportional Packing.',
        'ahb': {
            'bake_target': 'IMAGE_TEXTURES',
            'multires_bake': False,
            'resolution': '4096',
            'image_mode': 'ATLAS',
            'image_format': 'OPEN_EXR',
            'exr_codec': 'ZIP',
            'use_hdr_float': True,
            'auto_create_uv': True,
            'uv_mode': 'AUTO_SEAM',
            'auto_seam_angle': 30.0,
            'pack_enabled': True,
            'pack_world_scale': True,
            'pack_margin_px': 24,
            'samples': 512,
            'save_mode': 'EXTERNAL',
            'auto_save': True,
        },
        'tjs': {
            'portfolio_one_click': False,
            'export_format': 'GLB',
            'export_skins': True,
            'include_materials': True,
            'export_materials_mode': 'EXPORT',
            'include_textures': True,
            'image_format': 'AUTO',
            'compression': 'NONE',
            'animation_mode': 'ACTIONS',
            'export_all_actions': True,
            'sampling_fps': 30,
            'keyframe_reduction': False,
            'remove_static_tracks': False,
            'enable_animation_quantization': False,
        }
    }
}
